using System.Data;
using System.Text;

namespace ForgeORM.Core;

/// <summary>
/// Options used by db.AI.QueryAsync to keep natural-language SQL generation tenant-aware and safe by default.
/// </summary>
public sealed class ForgeAiQueryOptions
{
    /// <summary>Optional tenant id appended as a TenantId filter when the generated SQL can be safely constrained.</summary>
    public object? TenantId { get; set; }

    /// <summary>Optional entity/table name. Defaults to Orders for revenue/order-style prompts.</summary>
    public string? Entity { get; set; }

    /// <summary>Maximum number of rows returned by the generated SQL. Defaults to 100.</summary>
    public int Take { get; set; } = 100;

    /// <summary>Rejects non-read SQL. Enabled by default.</summary>
    public bool SafeMode { get; set; } = true;

    /// <summary>When true, result includes generated SQL and diagnostics.</summary>
    public bool IncludeSql { get; set; } = true;
}

/// <summary>
/// Result returned from db.AI.QueryAsync. Rows are dynamic dictionaries because AI projections are not known at compile time.
/// </summary>
public sealed record ForgeAiQueryResult(
    string Prompt,
    string Sql,
    IReadOnlyList<Dictionary<string, object?>> Rows,
    IReadOnlyList<string> Warnings,
    IReadOnlyList<string> Explanation);

/// <summary>Optimization suggestions generated by db.AI.OptimizeAsync.</summary>
public sealed record ForgeAiOptimizationResult(
    string OriginalSql,
    string OptimizedSql,
    IReadOnlyList<string> Suggestions,
    IReadOnlyList<string> SuggestedIndexes,
    IReadOnlyList<string> Warnings);

/// <summary>
/// AI facade exposed directly from ForgeDb/ForgeDbContext as db.AI.
/// This is intentionally routed through the existing ForgeDb query pipeline; no separate Fast API is introduced.
/// </summary>
public sealed class ForgeDbAiFacade
{
    private readonly ForgeDb _db;

    internal ForgeDbAiFacade(ForgeDb db) => _db = db;

    /// <summary>
    /// Converts a natural-language data question into safe SQL and executes it through ForgeORM.
    /// Example: await db.AI.QueryAsync("Top 10 customers by revenue last month", o => o.TenantId = tenantId, ct);
    /// </summary>
    public async ValueTask<ForgeAiQueryResult> QueryAsync(
        string prompt,
        Action<ForgeAiQueryOptions>? configure = null,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(prompt))
            throw new ArgumentException("AI query prompt cannot be empty.", nameof(prompt));

        var options = new ForgeAiQueryOptions();
        configure?.Invoke(options);

        var plan = BuildPlan(prompt, options);
        var rows = await _db.QueryDictionaryAsync(plan.Sql, plan.Parameters, cancellationToken: cancellationToken);

        return new ForgeAiQueryResult(
            prompt,
            options.IncludeSql ? plan.Sql : string.Empty,
            rows,
            plan.Warnings,
            plan.Explanation);
    }

    /// <summary>Analyzes SQL and returns optimization suggestions without executing the query.</summary>
    public ValueTask<ForgeAiOptimizationResult> OptimizeAsync(
        string sql,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(sql))
            throw new ArgumentException("SQL cannot be empty.", nameof(sql));

        cancellationToken.ThrowIfCancellationRequested();
        var suggestions = new List<string>();
        var indexes = new List<string>();
        var warnings = new List<string>();
        var optimized = sql.Trim();

        if (optimized.Contains("SELECT *", StringComparison.OrdinalIgnoreCase))
        {
            suggestions.Add("Replace SELECT * with an explicit projection to reduce IO and materialization cost.");
            warnings.Add("SELECT * can break compiled projection/read-shape caching when schema changes.");
        }

        if (optimized.Contains("ORDER BY", StringComparison.OrdinalIgnoreCase) && optimized.Contains("WHERE", StringComparison.OrdinalIgnoreCase))
        {
            suggestions.Add("Create a composite index covering the WHERE predicate columns followed by ORDER BY columns.");
            indexes.Add("IX_Orders_CustomerId_CreatedAt_DESC");
        }

        if (optimized.Contains("CustomerId", StringComparison.OrdinalIgnoreCase))
            indexes.Add("IX_Orders_CustomerId");

        if (optimized.Contains("CreatedAt", StringComparison.OrdinalIgnoreCase))
            indexes.Add("IX_Orders_CreatedAt");

        suggestions.Add("Use QueryAsync<T> with a DTO projection for a compiled reader shape.");
        suggestions.Add("Use seek pagination for large ordered result sets instead of deep OFFSET paging.");

        return ValueTask.FromResult(new ForgeAiOptimizationResult(
            sql,
            optimized,
            suggestions.Distinct(StringComparer.OrdinalIgnoreCase).ToArray(),
            indexes.Distinct(StringComparer.OrdinalIgnoreCase).ToArray(),
            warnings));
    }

    private static ForgeAiSqlPlan BuildPlan(string prompt, ForgeAiQueryOptions options)
    {
        var normalized = prompt.Trim().ToLowerInvariant();
        var table = string.IsNullOrWhiteSpace(options.Entity) ? "Orders" : options.Entity!.Trim();
        var take = options.Take <= 0 ? 100 : options.Take;
        var parameters = new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase);
        var warnings = new List<string>();
        var explanation = new List<string> { "Generated by ForgeORM deterministic AI query planner." };

        var where = new List<string>();
        if (options.TenantId is not null)
        {
            where.Add("TenantId = @TenantId");
            parameters["TenantId"] = options.TenantId;
            explanation.Add("Tenant filter was applied using @TenantId.");
        }

        if (normalized.Contains("last month", StringComparison.OrdinalIgnoreCase))
        {
            where.Add("CreatedAt >= DATEADD(month, DATEDIFF(month, 0, GETDATE()) - 1, 0)");
            where.Add("CreatedAt < DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)");
            explanation.Add("Date filter was applied for last month.");
        }

        var whereSql = where.Count == 0 ? string.Empty : "WHERE " + string.Join(" AND ", where);
        string sql;

        if ((normalized.Contains("top") || normalized.Contains("highest")) && normalized.Contains("customer") && normalized.Contains("revenue"))
        {
            sql = $"SELECT TOP ({Math.Min(take, 1000)}) CustomerId, SUM(GrandTotal) AS Revenue FROM {table} {whereSql} GROUP BY CustomerId ORDER BY Revenue DESC";
            explanation.Add("Recognized customer revenue ranking pattern.");
        }
        else if (normalized.Contains("revenue") && (normalized.Contains("month") || normalized.Contains("monthly")))
        {
            sql = $"SELECT YEAR(CreatedAt) AS [Year], MONTH(CreatedAt) AS [Month], SUM(GrandTotal) AS Revenue FROM {table} {whereSql} GROUP BY YEAR(CreatedAt), MONTH(CreatedAt) ORDER BY [Year] DESC, [Month] DESC";
            explanation.Add("Recognized monthly revenue analytics pattern.");
        }
        else if (normalized.Contains("count"))
        {
            sql = $"SELECT COUNT(1) AS Total FROM {table} {whereSql}";
            explanation.Add("Recognized count aggregation pattern.");
        }
        else
        {
            sql = $"SELECT TOP ({Math.Min(take, 1000)}) * FROM {table} {whereSql}";
            warnings.Add("Fallback SELECT was generated. Review projection before production use.");
        }

        if (options.SafeMode && !sql.TrimStart().StartsWith("SELECT", StringComparison.OrdinalIgnoreCase))
            throw new InvalidOperationException("ForgeORM AI safe mode only allows read-only SELECT queries.");

        return new ForgeAiSqlPlan(sql, parameters, warnings, explanation);
    }

    private sealed record ForgeAiSqlPlan(
        string Sql,
        IReadOnlyDictionary<string, object?> Parameters,
        IReadOnlyList<string> Warnings,
        IReadOnlyList<string> Explanation);
}

public partial class ForgeDb
{
    private ForgeDbAiFacade? _ai;

    /// <summary>
    /// AI query facade exposed directly from db. Example: await db.AI.QueryAsync("Top 10 customers by revenue last month", o => o.TenantId = tenantId, ct).
    /// </summary>
    public ForgeDbAiFacade AI => _ai ??= new ForgeDbAiFacade(this);
}
