using System.Data;
using System.Text;

namespace ForgeORM.Core;

/// <summary>Optimization suggestions generated by db.AI.OptimizeAsync.</summary>
public sealed record ForgeAiOptimizationResult(
    string OriginalSql,
    string OptimizedSql,
    IReadOnlyList<string> Suggestions,
    IReadOnlyList<string> SuggestedIndexes,
    IReadOnlyList<string> Warnings);
