using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ForgeORM.SourceGenerated;

/// <summary>
/// ForgeORM compile-time mapper generator.
/// Generates source-generated readers, parameter binders, SQL builders, graph metadata and entity maps.
/// The generated reader binds result columns by name once per reader shape and then uses strongly typed
/// DbDataReader.GetFieldValue<T> calls per row. Records/constructor DTOs are supported by matching
/// constructor parameter names to column/property names.
/// </summary>
[Generator]
public sealed class ForgeOrmGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax,
                static (ctx, _) => GetTypeSymbol(ctx))
            .Where(static x => x is not null)!;

        var compilationAndTypes = context.CompilationProvider.Combine(candidates.Collect());
        context.RegisterSourceOutput(compilationAndTypes, static (spc, source) => Execute(spc, source.Right!));
    }

    private static INamedTypeSymbol? GetTypeSymbol(GeneratorSyntaxContext context)
    {
        return context.Node switch
        {
            ClassDeclarationSyntax c => context.SemanticModel.GetDeclaredSymbol(c) as INamedTypeSymbol,
            RecordDeclarationSyntax r => context.SemanticModel.GetDeclaredSymbol(r) as INamedTypeSymbol,
            _ => null
        };
    }

    private static void Execute(SourceProductionContext context, IEnumerable<INamedTypeSymbol> allTypes)
    {
        var entityTypes = allTypes
            .Where(IsCandidateEntity)
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<INamedTypeSymbol>()
            .ToArray();

        if (entityTypes.Length == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using System.Data.Common;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using ForgeORM.Core;");
        sb.AppendLine("namespace ForgeORM.Generated;");
        sb.AppendLine();
        sb.AppendLine("public sealed class ForgeGeneratedAccessorProvider : IForgeSourceGeneratedAccessorProvider");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    public static void Register() => ForgeSourceGeneratedRegistry.Register(new ForgeGeneratedAccessorProvider());");
        sb.AppendLine();
        sb.AppendLine("    public bool CanHandle(Type type) => type.FullName switch");
        sb.AppendLine("    {");
        foreach (var type in entityTypes)
            sb.AppendLine("        \"" + Escape(type.ToDisplayString()) + "\" => true,");
        sb.AppendLine("        _ => false");
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public Func<DbDataReader, object> GetReader(Type type, DbDataReader reader) => type.FullName switch");
        sb.AppendLine("    {");
        foreach (var type in entityTypes)
            sb.AppendLine("        \"" + Escape(type.ToDisplayString()) + "\" => CreateReader_" + Safe(type) + "(reader),");
        sb.AppendLine("        _ => throw new InvalidOperationException($\"No ForgeORM generated reader for {type.FullName}.\")");
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public Action<DbCommand, object> GetBinder(Type type) => type.FullName switch");
        sb.AppendLine("    {");
        foreach (var type in entityTypes)
            sb.AppendLine("        \"" + Escape(type.ToDisplayString()) + "\" => Bind_" + Safe(type) + ",");
        sb.AppendLine("        _ => throw new InvalidOperationException($\"No ForgeORM generated binder for {type.FullName}.\")");
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public bool TryCreateReader<T>(DbDataReader reader, out Func<DbDataReader, T>? readerFunc)");
        sb.AppendLine("    {");
        foreach (var type in entityTypes)
        {
            sb.AppendLine("        if (typeof(T).FullName == \"" + Escape(type.ToDisplayString()) + "\")");
            sb.AppendLine("        {");
            sb.AppendLine("            readerFunc = (Func<DbDataReader, T>)(object)CreateReader_" + Safe(type) + "(reader);");
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
        }
        sb.AppendLine("        readerFunc = null;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public bool TryGetBinder(Type type, out Action<DbCommand, object>? binder)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!CanHandle(type))");
        sb.AppendLine("        {");
        sb.AppendLine("            binder = null;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine("        binder = GetBinder(type);");
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine();
        EmitHelpers(sb);

        foreach (var type in entityTypes)
        {
            EmitReaderFactory(sb, type);
            EmitBinder(sb, type);
            EmitSqlBuilder(sb, type);
            EmitGraphMetadata(sb, type);
            EmitEntityMap(sb, type);
        }

        sb.AppendLine("}");
        context.AddSource("ForgeORM.Generated.Accessors.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitHelpers(StringBuilder sb)
    {
        sb.AppendLine("    private static int Ordinal(DbDataReader reader, string name)");
        sb.AppendLine("        => ForgeColumnOrdinalShapeCache.GetOrdinalOrMinusOne(typeof(object), reader, name);");
        sb.AppendLine();
        sb.AppendLine("    private static TEnum ReadEnum<TEnum>(DbDataReader reader, int ordinal) where TEnum : struct, Enum");
        sb.AppendLine("    {");
        sb.AppendLine("        if (reader.IsDBNull(ordinal)) return default;");
        sb.AppendLine("        var value = reader.GetValue(ordinal);");
        sb.AppendLine("        if (value is string text) return Enum.Parse<TEnum>(text, ignoreCase: true);");
        sb.AppendLine("        return (TEnum)Enum.ToObject(typeof(TEnum), value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static TEnum? ReadNullableEnum<TEnum>(DbDataReader reader, int ordinal) where TEnum : struct, Enum");
        sb.AppendLine("    {");
        sb.AppendLine("        if (reader.IsDBNull(ordinal)) return null;");
        sb.AppendLine("        return ReadEnum<TEnum>(reader, ordinal);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static void Add(DbCommand command, string name, object? value, DbType? dbType = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        var parameterName = name[0] == '@' || name[0] == ':' ? name : \"@\" + name;");
        sb.AppendLine("        for (var i = 0; i < command.Parameters.Count; i++)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (command.Parameters[i] is not DbParameter existing) continue;");
        sb.AppendLine("            if (string.Equals(existing.ParameterName.TrimStart('@', ':'), parameterName.TrimStart('@', ':'), StringComparison.OrdinalIgnoreCase))");
        sb.AppendLine("            {");
        sb.AppendLine("                if (dbType.HasValue) existing.DbType = dbType.Value;");
        sb.AppendLine("                existing.Value = value ?? DBNull.Value;");
        sb.AppendLine("                return;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        var p = command.CreateParameter();");
        sb.AppendLine("        p.ParameterName = parameterName;");
        sb.AppendLine("        if (dbType.HasValue) p.DbType = dbType.Value;");
        sb.AppendLine("        p.Value = value ?? DBNull.Value;");
        sb.AppendLine("        command.Parameters.Add(p);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static bool IsCandidateEntity(INamedTypeSymbol type)
    {
        if (type.TypeKind is not (TypeKind.Class or TypeKind.Struct))
            return false;
        if (type.TypeKind == TypeKind.Class && type.IsAbstract)
            return false;
        if (type.DeclaredAccessibility != Accessibility.Public)
            return false;
        return HasForgeTableAttribute(type) || HasGenerateMapperAttribute(type) || HasForgeDtoAttribute(type) || HasForgeProjectionAttribute(type);
    }

    private static bool HasForgeTableAttribute(INamedTypeSymbol type)
        => type.GetAttributes().Any(a => a.AttributeClass?.Name is "ForgeTableAttribute" or "TableAttribute");

    private static bool HasGenerateMapperAttribute(INamedTypeSymbol type)
        => type.GetAttributes().Any(a => a.AttributeClass?.Name is "ForgeGenerateMapperAttribute" or "GenerateMapperAttribute");

    private static bool HasForgeDtoAttribute(INamedTypeSymbol type)
        => type.GetAttributes().Any(a => a.AttributeClass?.Name is "ForgeDtoAttribute" or "ForgeDTOAttribute" or "DtoAttribute" or "DTOAttribute");

    private static bool HasForgeProjectionAttribute(INamedTypeSymbol type)
        => type.GetAttributes().Any(a => a.AttributeClass?.Name is "ForgeProjectionAttribute" or "ProjectionAttribute");

    private static IEnumerable<IPropertySymbol> Properties(INamedTypeSymbol type)
        => type.GetMembers().OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic && p.GetMethod is not null && IsScalar(p.Type));

    private static IEnumerable<IPropertySymbol> WritableProperties(INamedTypeSymbol type)
        => Properties(type).Where(p => p.SetMethod is not null);

    private static bool IsScalar(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
            type = named.TypeArguments[0];
        if (type.TypeKind == TypeKind.Enum)
            return true;
        return type.SpecialType is SpecialType.System_String
            or SpecialType.System_Boolean
            or SpecialType.System_Byte
            or SpecialType.System_SByte
            or SpecialType.System_Int16
            or SpecialType.System_UInt16
            or SpecialType.System_Int32
            or SpecialType.System_UInt32
            or SpecialType.System_Int64
            or SpecialType.System_UInt64
            or SpecialType.System_Single
            or SpecialType.System_Double
            or SpecialType.System_Decimal
            or SpecialType.System_DateTime
            || type.ToDisplayString() is "System.Guid" or "System.DateTimeOffset" or "System.DateOnly" or "System.TimeOnly" or "System.TimeSpan" or "byte[]";
    }

    private static void EmitReaderFactory(StringBuilder sb, INamedTypeSymbol type)
    {
        var full = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var safe = Safe(type);
        var props = Properties(type).ToArray();
        var ctor = PickConstructor(type, props);
        var ctorParamProps = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        sb.AppendLine();
        sb.AppendLine("    private static Func<DbDataReader, object> CreateReader_" + safe + "(DbDataReader reader)");
        sb.AppendLine("    {");
        foreach (var p in props)
            sb.AppendLine("        var ord_" + p.Name + " = Ordinal(reader, \"" + Escape(ColumnName(p)) + "\");");
        sb.AppendLine("        return r =>");
        sb.AppendLine("        {");

        if (ctor is not null && ctor.Parameters.Length > 0)
        {
            sb.Append("            var entity = new ").Append(full).Append("(");
            for (var i = 0; i < ctor.Parameters.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                var parameter = ctor.Parameters[i];
                var prop = FindPropertyForParameter(props, parameter);
                if (prop is null)
                    sb.Append("default");
                else
                {
                    ctorParamProps.Add(prop.Name);
                    sb.Append(ReadOrDefaultExpression("r", "ord_" + prop.Name, parameter.Type));
                }
            }
            sb.AppendLine(");");
        }
        else
        {
            var parameterless = type.InstanceConstructors.Any(c => c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public);
            if (!parameterless)
            {
                // Compile-time diagnostic as generated code: clear failure when no constructor can be mapped.
                sb.AppendLine("            throw new InvalidOperationException(\"ForgeORM source generator could not find a parameterless constructor or a constructor whose parameter names match result columns for " + Escape(type.ToDisplayString()) + ".\");");
                sb.AppendLine("        };");
                sb.AppendLine("    }");
                return;
            }
            sb.AppendLine("            var entity = new " + full + "();");
        }

        foreach (var p in WritableProperties(type).Where(p => !ctorParamProps.Contains(p.Name)))
        {
            sb.AppendLine("            if (ord_" + p.Name + " >= 0 && !r.IsDBNull(ord_" + p.Name + ")) entity." + p.Name + " = " + ReadValueExpression("r", "ord_" + p.Name, p.Type) + ";");
        }

        sb.AppendLine("            return entity;");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    private static IMethodSymbol? PickConstructor(INamedTypeSymbol type, IPropertySymbol[] props)
    {
        var propNames = new HashSet<string>(props.Select(p => p.Name), StringComparer.OrdinalIgnoreCase);
        return type.InstanceConstructors
            .Where(c => c.DeclaredAccessibility == Accessibility.Public && c.Parameters.Length > 0)
            .OrderByDescending(c => c.Parameters.Length)
            .FirstOrDefault(c => c.Parameters.All(p => propNames.Contains(p.Name)));
    }

    private static IPropertySymbol? FindPropertyForParameter(IEnumerable<IPropertySymbol> props, IParameterSymbol parameter)
        => props.FirstOrDefault(p => string.Equals(p.Name, parameter.Name, StringComparison.OrdinalIgnoreCase));

    private static string ReadOrDefaultExpression(string readerName, string ordinalName, ITypeSymbol type)
        => ordinalName + " >= 0 && !" + readerName + ".IsDBNull(" + ordinalName + ") ? " + ReadValueExpression(readerName, ordinalName, type) + " : default!";

    private static string ReadValueExpression(string readerName, string ordinalName, ITypeSymbol type)
    {
        var nullable = type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nts ? nts.TypeArguments[0] : type;
        var full = nullable.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        if (nullable.TypeKind == TypeKind.Enum)
        {
            if (!SymbolEqualityComparer.Default.Equals(nullable, type))
                return "ReadNullableEnum<" + full + ">(" + readerName + ", " + ordinalName + ")!.Value";
            return "ReadEnum<" + full + ">(" + readerName + ", " + ordinalName + ")";
        }

        return full switch
        {
            "int" or "global::System.Int32" => readerName + ".GetInt32(" + ordinalName + ")",
            "long" or "global::System.Int64" => readerName + ".GetInt64(" + ordinalName + ")",
            "short" or "global::System.Int16" => readerName + ".GetInt16(" + ordinalName + ")",
            "bool" or "global::System.Boolean" => readerName + ".GetBoolean(" + ordinalName + ")",
            "decimal" or "global::System.Decimal" => readerName + ".GetDecimal(" + ordinalName + ")",
            "double" or "global::System.Double" => readerName + ".GetDouble(" + ordinalName + ")",
            "float" or "global::System.Single" => readerName + ".GetFloat(" + ordinalName + ")",
            "string" or "global::System.String" => readerName + ".GetString(" + ordinalName + ")",
            "global::System.Guid" => readerName + ".GetGuid(" + ordinalName + ")",
            "global::System.DateTime" => readerName + ".GetDateTime(" + ordinalName + ")",
            _ => readerName + ".GetFieldValue<" + full + ">(" + ordinalName + ")"
        };
    }

    private static void EmitBinder(StringBuilder sb, INamedTypeSymbol type)
    {
        var full = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        sb.AppendLine();
        sb.AppendLine("    private static void Bind_" + Safe(type) + "(DbCommand command, object value)");
        sb.AppendLine("    {");
        sb.AppendLine("        var entity = (" + full + ")value;");
        foreach (var p in Properties(type))
            sb.AppendLine("        Add(command, \"" + Escape(p.Name) + "\", entity." + p.Name + ");");
        sb.AppendLine("    }");
    }

    private static void EmitSqlBuilder(StringBuilder sb, INamedTypeSymbol type)
    {
        var table = TableName(type);
        var safe = Safe(type);
        var columns = Properties(type).ToArray();
        var insertable = columns.Where(p => !IsComputed(p) && !IsKeyIdentity(p)).ToArray();
        var updateable = columns.Where(p => !IsComputed(p) && !IsKey(p)).ToArray();
        var key = columns.FirstOrDefault(IsKey) ?? columns.FirstOrDefault(p => string.Equals(p.Name, "Id", StringComparison.OrdinalIgnoreCase));

        sb.AppendLine();
        sb.AppendLine("    public static string SelectSql_" + safe + " => \"SELECT " + Escape(string.Join(", ", columns.Select(p => ColumnName(p)))) + " FROM " + Escape(table) + "\";");
        sb.AppendLine("    public static string InsertSql_" + safe + " => \"INSERT INTO " + Escape(table) + " (" + Escape(string.Join(", ", insertable.Select(ColumnName))) + ") VALUES (" + Escape(string.Join(", ", insertable.Select(p => "@" + p.Name))) + ")\";");
        if (key is not null)
            sb.AppendLine("    public static string UpdateSql_" + safe + " => \"UPDATE " + Escape(table) + " SET " + Escape(string.Join(", ", updateable.Select(p => ColumnName(p) + " = @" + p.Name))) + " WHERE " + Escape(ColumnName(key)) + " = @" + Escape(key.Name) + "\";");
        if (key is not null)
            sb.AppendLine("    public static string DeleteSql_" + safe + " => \"DELETE FROM " + Escape(table) + " WHERE " + Escape(ColumnName(key)) + " = @" + Escape(key.Name) + "\";");
    }

    private static void EmitGraphMetadata(StringBuilder sb, INamedTypeSymbol type)
    {
        sb.AppendLine("    public static string GraphMetadata_" + Safe(type) + " => \"" + Escape(type.ToDisplayString()) + "|" + Escape(TableName(type)) + "\";");
    }

    private static void EmitEntityMap(StringBuilder sb, INamedTypeSymbol type)
    {
        var cols = string.Join("|", Properties(type).Select(p => p.Name + ":" + ColumnName(p)));
        sb.AppendLine("    public static string EntityMap_" + Safe(type) + " => \"" + Escape(type.ToDisplayString()) + "|" + Escape(TableName(type)) + "|" + Escape(cols) + "\";");
    }

    private static bool IsKey(IPropertySymbol p) => p.GetAttributes().Any(a => a.AttributeClass?.Name is "ForgeKeyAttribute" or "KeyAttribute") || string.Equals(p.Name, "Id", StringComparison.OrdinalIgnoreCase);
    private static bool IsKeyIdentity(IPropertySymbol p) => IsKey(p);
    private static bool IsComputed(IPropertySymbol p) => p.GetAttributes().Any(a => a.AttributeClass?.Name is "ForgeComputedAttribute" or "ComputedAttribute");

    private static string ColumnName(IPropertySymbol property)
        => property.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name is "ForgeColumnAttribute" or "ColumnAttribute")?.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? property.Name;

    private static string TableName(INamedTypeSymbol type)
        => type.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name is "ForgeTableAttribute" or "TableAttribute")?.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? type.Name;

    private static string Safe(INamedTypeSymbol type)
        => type.ToDisplayString().Replace('.', '_').Replace('+', '_').Replace('<', '_').Replace('>', '_').Replace(',', '_').Replace(' ', '_');

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
