using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ForgeORM.SourceGenerated;

/// <summary>
/// ForgeORM compile-time mapper generator.
/// Generates source-generated readers, parameter binders, SQL builders, graph metadata and entity maps.
/// The generated reader binds result columns by name once per reader shape and then uses strongly typed
/// DbDataReader.GetFieldValue<T> calls per row. Records/constructor DTOs are supported by matching
/// constructor parameter names to column/property names.
/// </summary>
[Generator]
public sealed class ForgeOrmGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax,
                static (ctx, _) => GetTypeSymbol(ctx))
            .Where(static x => x is not null)!;

        var compilationAndTypes = context.CompilationProvider.Combine(candidates.Collect());
        context.RegisterSourceOutput(compilationAndTypes, static (spc, source) => Execute(spc, source.Right!));
    }

    private static INamedTypeSymbol? GetTypeSymbol(GeneratorSyntaxContext context)
    {
        return context.Node switch
        {
            ClassDeclarationSyntax c => context.SemanticModel.GetDeclaredSymbol(c) as INamedTypeSymbol,
            RecordDeclarationSyntax r => context.SemanticModel.GetDeclaredSymbol(r) as INamedTypeSymbol,
            _ => null
        };
    }

    private static void Execute(SourceProductionContext context, IEnumerable<INamedTypeSymbol> allTypes)
    {
        var entityTypes = allTypes
            .Where(IsCandidateEntity)
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<INamedTypeSymbol>()
            .ToArray();

        if (entityTypes.Length == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using System.Data.Common;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using ForgeORM.Core;");
        sb.AppendLine("using ForgeORM.Abstractions;");
        sb.AppendLine("using Microsoft.Data.SqlClient;");
        sb.AppendLine("namespace ForgeORM.Generated;");
        sb.AppendLine();
        sb.AppendLine("public sealed class ForgeGeneratedAccessorProvider : IForgeSourceGeneratedAccessorProvider");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    public static void Register()");
        sb.AppendLine("    {");
        sb.AppendLine("        var provider = new ForgeGeneratedAccessorProvider();");
        sb.AppendLine("        ForgeSourceGeneratedRegistry.Register(provider);");
        foreach (var type in entityTypes)
            EmitMetadataRegistration(sb, type);
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public bool CanHandle(Type type) => type.FullName switch");
        sb.AppendLine("    {");
        foreach (var type in entityTypes)
            sb.AppendLine("        \"" + Escape(type.ToDisplayString()) + "\" => true,");
        sb.AppendLine("        _ => false");
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public Func<DbDataReader, object> GetReader(Type type, DbDataReader reader) => type.FullName switch");
        sb.AppendLine("    {");
        foreach (var type in entityTypes)
            sb.AppendLine("        \"" + Escape(type.ToDisplayString()) + "\" => CreateReader_" + Safe(type) + "(reader),");
        sb.AppendLine("        _ => throw new InvalidOperationException($\"No ForgeORM generated reader for {type.FullName}.\")");
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public Action<DbCommand, object> GetBinder(Type type) => type.FullName switch");
        sb.AppendLine("    {");
        foreach (var type in entityTypes)
            sb.AppendLine("        \"" + Escape(type.ToDisplayString()) + "\" => Bind_" + Safe(type) + ",");
        sb.AppendLine("        _ => throw new InvalidOperationException($\"No ForgeORM generated binder for {type.FullName}.\")");
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public bool TryCreateReader<T>(DbDataReader reader, out Func<DbDataReader, T>? readerFunc)");
        sb.AppendLine("    {");
        foreach (var type in entityTypes)
        {
            sb.AppendLine("        if (typeof(T).FullName == \"" + Escape(type.ToDisplayString()) + "\")");
            sb.AppendLine("        {");
            sb.AppendLine("            readerFunc = (Func<DbDataReader, T>)(object)CreateReader_" + Safe(type) + "(reader);");
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
        }
        sb.AppendLine("        readerFunc = null;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public bool TryGetBinder(Type type, out Action<DbCommand, object>? binder)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!CanHandle(type))");
        sb.AppendLine("        {");
        sb.AppendLine("            binder = null;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine("        binder = GetBinder(type);");
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine();        sb.AppendLine("    public bool TryGetTypedBinder<T>(out IForgeParameterBinder<T>? binder)");
        sb.AppendLine("    {");
        foreach (var type in entityTypes)
        {
            sb.AppendLine("        if (typeof(T).FullName == \"" + Escape(type.ToDisplayString()) + "\")");
            sb.AppendLine("        {");
            sb.AppendLine("            binder = (IForgeParameterBinder<T>)(object)new Binder_" + Safe(type) + "();");
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
        }
        sb.AppendLine("        binder = null;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public bool TryExecuteFirstOrDefaultAsync<T>(DbConnection connection, string sql, object? parameters, DbTransaction? transaction, CommandType commandType, int? timeoutSeconds, CancellationToken cancellationToken, out ValueTask<T?> result)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!IsGeneratedQueryCandidate(sql, commandType))");
        sb.AppendLine("        {");
        sb.AppendLine("            result = default;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        foreach (var type in entityTypes)
        {
            sb.AppendLine("        if (typeof(T).FullName == " + Escape(type.ToDisplayString()) + ")");
            sb.AppendLine("        {");
            sb.AppendLine("            result = (ValueTask<T?>)(object)ExecuteProviderFirst_" + Safe(type) + "(connection, sql, parameters, transaction, commandType, timeoutSeconds, cancellationToken);");
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
        }
        sb.AppendLine("        result = default;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public bool TryExecuteQueryAsync<T>(DbConnection connection, string sql, object? parameters, DbTransaction? transaction, CommandType commandType, int? timeoutSeconds, CancellationToken cancellationToken, out ValueTask<IReadOnlyList<T>> result)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!IsGeneratedQueryCandidate(sql, commandType))");
        sb.AppendLine("        {");
        sb.AppendLine("            result = default;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        foreach (var type in entityTypes)
        {
            sb.AppendLine("        if (typeof(T).FullName == " + Escape(type.ToDisplayString()) + ")");
            sb.AppendLine("        {");
            sb.AppendLine("            result = (ValueTask<IReadOnlyList<T>>)(object)ExecuteProviderQuery_" + Safe(type) + "(connection, sql, parameters, transaction, commandType, timeoutSeconds, cancellationToken);");
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
        }
        sb.AppendLine("        result = default;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public bool TryExecuteSqlServerFirstOrDefaultAsync<T>(string connectionString, string sql, object? parameters, int? timeoutSeconds, CancellationToken cancellationToken, out ValueTask<T?> result)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!IsGeneratedQueryCandidate(sql, CommandType.Text))");
        sb.AppendLine("        {");
        sb.AppendLine("            result = default;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        foreach (var type in entityTypes)
        {
            sb.AppendLine("        if (typeof(T).FullName == \"" + Escape(type.ToDisplayString()) + "\")");
            sb.AppendLine("        {");
            sb.AppendLine("            result = (ValueTask<T?>)(object)ExecuteSqlServerFirst_" + Safe(type) + "(connectionString, sql, parameters, timeoutSeconds, cancellationToken);");
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
        }
        sb.AppendLine("        result = default;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
        EmitHelpers(sb);

        foreach (var type in entityTypes)
        {
            EmitReaderFactory(sb, type);
            EmitProviderNeutralExecutors(sb, type);
            EmitSqlServerFirstExecutor(sb, type);
            EmitBinder(sb, type);
            EmitSqlBuilder(sb, type);
            EmitGraphMetadata(sb, type);
            EmitEntityMap(sb, type);
        }

        sb.AppendLine("}");
        context.AddSource("ForgeORM.Generated.Accessors.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }


    private static void EmitMetadataRegistration(StringBuilder sb, INamedTypeSymbol type)
    {
        var full = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var props = Properties(type).ToArray();
        var keys = props.Where(IsKey).ToArray();
        var keyColumn = keys.Length > 0 ? ColumnName(keys[0]) : "Id";
        var code = props.FirstOrDefault(p => string.Equals(p.Name, "Code", StringComparison.OrdinalIgnoreCase));
        var codeColumn = code is null ? "Code" : ColumnName(code);

        sb.AppendLine("        ForgeSourceGeneratedRegistry.RegisterMetadata(typeof(" + full + "), new ForgeEntityMetadata");
        sb.AppendLine("        {");
        sb.AppendLine("            EntityType = typeof(" + full + "),");
        sb.AppendLine("            TableName = \"" + Escape(TableName(type)) + "\",");
        sb.AppendLine("            KeyColumn = \"" + Escape(keyColumn) + "\",");
        sb.AppendLine("            CodeColumn = \"" + Escape(codeColumn) + "\",");
        sb.AppendLine("            Properties = new ForgePropertyMetadata[]");
        sb.AppendLine("            {");
        foreach (var p in props)
        {
            var isKey = keys.Any(k => SymbolEqualityComparer.Default.Equals(k, p)) ? "true" : "false";
            var isCode = string.Equals(p.Name, "Code", StringComparison.OrdinalIgnoreCase) || p.GetAttributes().Any(a => a.AttributeClass?.Name is "ForgeCodeAttribute" or "CodeAttribute") ? "true" : "false";
            var isComputed = IsComputed(p) ? "true" : "false";
            var typeName = p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine("                new ForgePropertyMetadata");
            sb.AppendLine("                {");
            sb.AppendLine("                    PropertyName = \"" + Escape(p.Name) + "\",");
            sb.AppendLine("                    ColumnName = \"" + Escape(ColumnName(p)) + "\",");
            sb.AppendLine("                    PropertyType = typeof(" + typeName + "),");
            sb.AppendLine("                    IsKey = " + isKey + ",");
            sb.AppendLine("                    IsCode = " + isCode + ",");
            sb.AppendLine("                    IsComputed = " + isComputed);
            sb.AppendLine("                },");
        }
        sb.AppendLine("            }");
        sb.AppendLine("        });");
    }

    private static void EmitHelpers(StringBuilder sb)
    {
        sb.AppendLine("    private static int Ordinal(DbDataReader reader, string name)");
        sb.AppendLine("        => ForgeColumnOrdinalShapeCache.GetOrdinalOrMinusOne(typeof(object), reader, name);");
        sb.AppendLine();
        sb.AppendLine("    private static TEnum ReadEnum<TEnum>(DbDataReader reader, int ordinal) where TEnum : struct, Enum");
        sb.AppendLine("    {");
        sb.AppendLine("        if (reader.IsDBNull(ordinal)) return default;");
        sb.AppendLine("        var value = reader.GetValue(ordinal);");
        sb.AppendLine("        if (value is string text) return Enum.Parse<TEnum>(text, ignoreCase: true);");
        sb.AppendLine(@"        var underlying = Enum.GetUnderlyingType(typeof(TEnum));
        return (TEnum)Enum.ToObject(typeof(TEnum), Convert.ChangeType(value, underlying));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static TEnum? ReadNullableEnum<TEnum>(DbDataReader reader, int ordinal) where TEnum : struct, Enum");
        sb.AppendLine("    {");
        sb.AppendLine("        if (reader.IsDBNull(ordinal)) return null;");
        sb.AppendLine("        return ReadEnum<TEnum>(reader, ordinal);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static bool IsGeneratedQueryCandidate(string sql, CommandType commandType)");
        sb.AppendLine("        => commandType == CommandType.Text && !string.IsNullOrWhiteSpace(sql) && sql.IndexOf(\" IN \", StringComparison.OrdinalIgnoreCase) < 0;");
        sb.AppendLine();
        sb.AppendLine("    private static string[] SqlParameterNames(string sql)");
        sb.AppendLine("    {");
        sb.AppendLine("        var names = new global::System.Collections.Generic.List<string>(4);");
        sb.AppendLine("        for (var i = 0; i < sql.Length; i++)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (sql[i] is not '@' and not ':') continue;");
        sb.AppendLine("            var start = i++;");
        sb.AppendLine("            if (i >= sql.Length || !(char.IsLetter(sql[i]) || sql[i] == '_')) continue;");
        sb.AppendLine("            while (i < sql.Length && (char.IsLetterOrDigit(sql[i]) || sql[i] == '_')) i++;");
        sb.AppendLine("            var name = sql.Substring(start, i - start);");
        sb.AppendLine("            var exists = false;");
        sb.AppendLine("            for (var n = 0; n < names.Count; n++) if (string.Equals(names[n], name, StringComparison.OrdinalIgnoreCase)) { exists = true; break; }");
        sb.AppendLine("            if (!exists) names.Add(name);");
        sb.AppendLine("        }");
        sb.AppendLine("        return names.Count == 0 ? Array.Empty<string>() : names.ToArray();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static string FirstSqlParameterName(string sql)");
        sb.AppendLine("    {");
        sb.AppendLine("        var names = SqlParameterNames(sql);");
        sb.AppendLine("        return names.Length == 0 ? \"@Id\" : names[0];");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static object? ExtractParameterValue(object? parameters, string name)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (parameters is null) return null;");
        sb.AppendLine("        var clean = name.TrimStart('@', ':');");
        sb.AppendLine("        if (parameters is System.Collections.Generic.IReadOnlyDictionary<string, object?> ro)");
        sb.AppendLine("            return ro.TryGetValue(clean, out var v) || ro.TryGetValue(name, out v) ? v : null;");
        sb.AppendLine("        if (parameters is System.Collections.IDictionary d)");
        sb.AppendLine("            return d.Contains(clean) ? d[clean] : d.Contains(name) ? d[name] : null;");
        sb.AppendLine("        var type = parameters.GetType();");
        sb.AppendLine("        if (type.IsPrimitive || type.IsEnum || parameters is string or decimal or Guid or DateTime or DateTimeOffset)");
        sb.AppendLine("            return parameters;");
        sb.AppendLine("        var prop = type.GetProperty(clean, System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.IgnoreCase);");
        sb.AppendLine("        return prop?.GetValue(parameters);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static void AddSqlParameter(SqlCommand command, string name, object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!name.StartsWith(\"@\", StringComparison.Ordinal)) name = \"@\" + name;");
        sb.AppendLine("        var type = value?.GetType();");
        sb.AppendLine("        type = type is null ? typeof(string) : Nullable.GetUnderlyingType(type) ?? type;");
        sb.AppendLine("        SqlParameter p;");
        sb.AppendLine("        if (type == typeof(int)) p = command.Parameters.Add(name, System.Data.SqlDbType.Int);");
        sb.AppendLine("        else if (type == typeof(long)) p = command.Parameters.Add(name, System.Data.SqlDbType.BigInt);");
        sb.AppendLine("        else if (type == typeof(short)) p = command.Parameters.Add(name, System.Data.SqlDbType.SmallInt);");
        sb.AppendLine("        else if (type == typeof(byte)) p = command.Parameters.Add(name, System.Data.SqlDbType.TinyInt);");
        sb.AppendLine("        else if (type == typeof(Guid)) p = command.Parameters.Add(name, System.Data.SqlDbType.UniqueIdentifier);");
        sb.AppendLine("        else if (type == typeof(decimal)) p = command.Parameters.Add(name, System.Data.SqlDbType.Decimal);");
        sb.AppendLine("        else if (type == typeof(double)) p = command.Parameters.Add(name, System.Data.SqlDbType.Float);");
        sb.AppendLine("        else if (type == typeof(float)) p = command.Parameters.Add(name, System.Data.SqlDbType.Real);");
        sb.AppendLine("        else if (type == typeof(bool)) p = command.Parameters.Add(name, System.Data.SqlDbType.Bit);");
        sb.AppendLine("        else if (type == typeof(DateTime)) p = command.Parameters.Add(name, System.Data.SqlDbType.DateTime2);");
        sb.AppendLine("        else if (type == typeof(DateTimeOffset)) p = command.Parameters.Add(name, System.Data.SqlDbType.DateTimeOffset);");
        sb.AppendLine("        else p = command.Parameters.Add(name, System.Data.SqlDbType.NVarChar);");
        sb.AppendLine("        p.Value = type.IsEnum && value is not null ? Convert.ChangeType(value, Enum.GetUnderlyingType(type)) : value ?? DBNull.Value;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static void AddDbParameters(DbCommand command, string sql, object? parameters)");
        sb.AppendLine("    {");
        sb.AppendLine("        var names = SqlParameterNames(sql);");
        sb.AppendLine("        for (var i = 0; i < names.Length; i++)");
        sb.AppendLine("            Add(command, names[i], ExtractParameterValue(parameters, names[i]));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static void Add(DbCommand command, string name, object? value, DbType? dbType = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        var parameterName = name[0] == '@' || name[0] == ':' ? name : \"@\" + name;");
        sb.AppendLine("        for (var i = 0; i < command.Parameters.Count; i++)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (command.Parameters[i] is not DbParameter existing) continue;");
        sb.AppendLine("            if (string.Equals(existing.ParameterName.TrimStart('@', ':'), parameterName.TrimStart('@', ':'), StringComparison.OrdinalIgnoreCase))");
        sb.AppendLine("            {");
        sb.AppendLine("                if (dbType.HasValue) existing.DbType = dbType.Value;");
        sb.AppendLine("                existing.Value = value ?? DBNull.Value;");
        sb.AppendLine("                return;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        var p = command.CreateParameter();");
        sb.AppendLine("        p.ParameterName = parameterName;");
        sb.AppendLine("        if (dbType.HasValue) p.DbType = dbType.Value;");
        sb.AppendLine("        p.Value = value ?? DBNull.Value;");
        sb.AppendLine("        command.Parameters.Add(p);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static bool IsCandidateEntity(INamedTypeSymbol type)
    {
        if (type.TypeKind is not (TypeKind.Class or TypeKind.Struct))
            return false;
        if (type.TypeKind == TypeKind.Class && type.IsAbstract)
            return false;
        if (type.DeclaredAccessibility != Accessibility.Public)
            return false;
        return HasForgeTableAttribute(type) || HasGenerateMapperAttribute(type) || HasForgeDtoAttribute(type) || HasForgeProjectionAttribute(type);
    }

    private static bool HasForgeTableAttribute(INamedTypeSymbol type)
        => type.GetAttributes().Any(a => a.AttributeClass?.Name is "ForgeTableAttribute" or "TableAttribute");

    private static bool HasGenerateMapperAttribute(INamedTypeSymbol type)
        => type.GetAttributes().Any(a => a.AttributeClass?.Name is "ForgeGenerateMapperAttribute" or "GenerateMapperAttribute");

    private static bool HasForgeDtoAttribute(INamedTypeSymbol type)
        => type.GetAttributes().Any(a => a.AttributeClass?.Name is "ForgeDtoAttribute" or "ForgeDTOAttribute" or "DtoAttribute" or "DTOAttribute");

    private static bool HasForgeProjectionAttribute(INamedTypeSymbol type)
        => type.GetAttributes().Any(a => a.AttributeClass?.Name is "ForgeProjectionAttribute" or "ProjectionAttribute");

    private static IEnumerable<IPropertySymbol> Properties(INamedTypeSymbol type)
        => type.GetMembers().OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic && p.GetMethod is not null && IsScalar(p.Type));

    private static IEnumerable<IPropertySymbol> WritableProperties(INamedTypeSymbol type)
        => Properties(type).Where(p => p.SetMethod is not null);

    private static bool IsScalar(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
            type = named.TypeArguments[0];
        if (type.TypeKind == TypeKind.Enum)
            return true;
        return type.SpecialType is SpecialType.System_String
            or SpecialType.System_Boolean
            or SpecialType.System_Byte
            or SpecialType.System_SByte
            or SpecialType.System_Int16
            or SpecialType.System_UInt16
            or SpecialType.System_Int32
            or SpecialType.System_UInt32
            or SpecialType.System_Int64
            or SpecialType.System_UInt64
            or SpecialType.System_Single
            or SpecialType.System_Double
            or SpecialType.System_Decimal
            or SpecialType.System_DateTime
            || type.ToDisplayString() is "System.Guid" or "System.DateTimeOffset" or "System.DateOnly" or "System.TimeOnly" or "System.TimeSpan" or "byte[]";
    }

    private static void EmitReaderFactory(StringBuilder sb, INamedTypeSymbol type)
    {
        var full = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var safe = Safe(type);
        var props = Properties(type).ToArray();
        var ctor = PickConstructor(type, props);
        var ctorParamProps = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        sb.AppendLine();
        sb.AppendLine("    private static Func<DbDataReader, object> CreateReader_" + safe + "(DbDataReader reader)");
        sb.AppendLine("    {");
        foreach (var p in props)
            sb.AppendLine("        var ord_" + p.Name + " = Ordinal(reader, \"" + Escape(ColumnName(p)) + "\");");
        sb.AppendLine("        return r =>");
        sb.AppendLine("        {");

        if (ctor is not null && ctor.Parameters.Length > 0)
        {
            sb.Append("            var entity = new ").Append(full).Append("(");
            for (var i = 0; i < ctor.Parameters.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                var parameter = ctor.Parameters[i];
                var prop = FindPropertyForParameter(props, parameter);
                if (prop is null)
                    sb.Append("default");
                else
                {
                    ctorParamProps.Add(prop.Name);
                    sb.Append(ReadOrDefaultExpression("r", "ord_" + prop.Name, parameter.Type));
                }
            }
            sb.AppendLine(");");
        }
        else
        {
            var parameterless = type.InstanceConstructors.Any(c => c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public);
            if (!parameterless)
            {
                // Compile-time diagnostic as generated code: clear failure when no constructor can be mapped.
                sb.AppendLine("            throw new InvalidOperationException(\"ForgeORM source generator could not find a parameterless constructor or a constructor whose parameter names match result columns for " + Escape(type.ToDisplayString()) + ".\");");
                sb.AppendLine("        };");
                sb.AppendLine("    }");
                return;
            }
            sb.AppendLine("            var entity = new " + full + "();");
        }

        foreach (var p in WritableProperties(type).Where(p => !ctorParamProps.Contains(p.Name)))
        {
            sb.AppendLine("            if (ord_" + p.Name + " >= 0 && !r.IsDBNull(ord_" + p.Name + ")) entity." + p.Name + " = " + ReadValueExpression("r", "ord_" + p.Name, p.Type) + ";");
        }

        sb.AppendLine("            return entity;");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    private static IMethodSymbol? PickConstructor(INamedTypeSymbol type, IPropertySymbol[] props)
    {
        var propNames = new HashSet<string>(props.Select(p => p.Name), StringComparer.OrdinalIgnoreCase);
        return type.InstanceConstructors
            .Where(c => c.DeclaredAccessibility == Accessibility.Public && c.Parameters.Length > 0)
            .OrderByDescending(c => c.Parameters.Length)
            .FirstOrDefault(c => c.Parameters.All(p => propNames.Contains(p.Name)));
    }

    private static IPropertySymbol? FindPropertyForParameter(IEnumerable<IPropertySymbol> props, IParameterSymbol parameter)
        => props.FirstOrDefault(p => string.Equals(p.Name, parameter.Name, StringComparison.OrdinalIgnoreCase));

    private static string ReadOrDefaultExpression(string readerName, string ordinalName, ITypeSymbol type)
        => ordinalName + " >= 0 && !" + readerName + ".IsDBNull(" + ordinalName + ") ? " + ReadValueExpression(readerName, ordinalName, type) + " : default!";

    private static string ReadValueExpression(string readerName, string ordinalName, ITypeSymbol type)
    {
        var nullable = type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nts ? nts.TypeArguments[0] : type;
        var full = nullable.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        if (nullable.TypeKind == TypeKind.Enum)
        {
            if (!SymbolEqualityComparer.Default.Equals(nullable, type))
                return "ReadNullableEnum<" + full + ">(" + readerName + ", " + ordinalName + ")!.Value";
            return "ReadEnum<" + full + ">(" + readerName + ", " + ordinalName + ")";
        }

        return full switch
        {
            "int" or "global::System.Int32" => readerName + ".GetInt32(" + ordinalName + ")",
            "long" or "global::System.Int64" => readerName + ".GetInt64(" + ordinalName + ")",
            "short" or "global::System.Int16" => readerName + ".GetInt16(" + ordinalName + ")",
            "bool" or "global::System.Boolean" => readerName + ".GetBoolean(" + ordinalName + ")",
            "decimal" or "global::System.Decimal" => readerName + ".GetDecimal(" + ordinalName + ")",
            "double" or "global::System.Double" => readerName + ".GetDouble(" + ordinalName + ")",
            "float" or "global::System.Single" => readerName + ".GetFloat(" + ordinalName + ")",
            "string" or "global::System.String" => readerName + ".GetString(" + ordinalName + ")",
            "global::System.Guid" => readerName + ".GetGuid(" + ordinalName + ")",
            "global::System.DateTime" => readerName + ".GetDateTime(" + ordinalName + ")",
            _ => readerName + ".GetFieldValue<" + full + ">(" + ordinalName + ")"
        };
    }



    private static void EmitProviderNeutralExecutors(StringBuilder sb, INamedTypeSymbol type)
    {
        var full = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var safe = Safe(type);
        var props = Properties(type).ToArray();
        var ctor = PickConstructor(type, props);

        sb.AppendLine();
        sb.AppendLine("    private static async ValueTask<" + full + "?> ExecuteProviderFirst_" + safe + "(DbConnection connection, string sql, object? parameters, DbTransaction? transaction, CommandType commandType, int? timeoutSeconds, CancellationToken cancellationToken)");
        sb.AppendLine("    {");
        sb.AppendLine("        var shouldClose = connection.State != ConnectionState.Open;");
        sb.AppendLine("        if (shouldClose) await connection.OpenAsync(cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            await using var command = connection.CreateCommand();");
        sb.AppendLine("            command.CommandText = sql;");
        sb.AppendLine("            command.CommandType = commandType;");
        sb.AppendLine("            if (transaction is not null) command.Transaction = transaction;");
        sb.AppendLine("            if (timeoutSeconds.HasValue) command.CommandTimeout = timeoutSeconds.Value;");
        sb.AppendLine("            AddDbParameters(command, sql, parameters);");
        sb.AppendLine("            await using var reader = await command.ExecuteReaderAsync(CommandBehavior.SingleRow | CommandBehavior.SequentialAccess, cancellationToken).ConfigureAwait(false);");
        foreach (var p in props)
            sb.AppendLine("            var ord_" + p.Name + " = Ordinal(reader, \"" + Escape(ColumnName(p)) + "\");");
        sb.AppendLine("            if (!await reader.ReadAsync(cancellationToken).ConfigureAwait(false)) return default;");
        EmitEntityMaterializationInto(sb, type, props, ctor, "reader", "            ");
        sb.AppendLine("            return entity;");
        sb.AppendLine("        }");
        sb.AppendLine("        finally");
        sb.AppendLine("        {");
        sb.AppendLine("            if (shouldClose) await connection.CloseAsync().ConfigureAwait(false);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine();
        sb.AppendLine("    private static async ValueTask<IReadOnlyList<" + full + ">> ExecuteProviderQuery_" + safe + "(DbConnection connection, string sql, object? parameters, DbTransaction? transaction, CommandType commandType, int? timeoutSeconds, CancellationToken cancellationToken)");
        sb.AppendLine("    {");
        sb.AppendLine("        var shouldClose = connection.State != ConnectionState.Open;");
        sb.AppendLine("        if (shouldClose) await connection.OpenAsync(cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            await using var command = connection.CreateCommand();");
        sb.AppendLine("            command.CommandText = sql;");
        sb.AppendLine("            command.CommandType = commandType;");
        sb.AppendLine("            if (transaction is not null) command.Transaction = transaction;");
        sb.AppendLine("            if (timeoutSeconds.HasValue) command.CommandTimeout = timeoutSeconds.Value;");
        sb.AppendLine("            AddDbParameters(command, sql, parameters);");
        sb.AppendLine("            await using var reader = await command.ExecuteReaderAsync(CommandBehavior.SequentialAccess, cancellationToken).ConfigureAwait(false);");
        foreach (var p in props)
            sb.AppendLine("            var ord_" + p.Name + " = Ordinal(reader, \"" + Escape(ColumnName(p)) + "\");");
        sb.AppendLine("            var rows = new global::System.Collections.Generic.List<" + full + ">(32);");
        sb.AppendLine("            while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))");
        sb.AppendLine("            {");
        EmitEntityMaterializationInto(sb, type, props, ctor, "reader", "                ");
        sb.AppendLine("                rows.Add(entity);");
        sb.AppendLine("            }");
        sb.AppendLine("            return rows;");
        sb.AppendLine("        }");
        sb.AppendLine("        finally");
        sb.AppendLine("        {");
        sb.AppendLine("            if (shouldClose) await connection.CloseAsync().ConfigureAwait(false);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static void EmitEntityMaterializationInto(StringBuilder sb, INamedTypeSymbol type, IPropertySymbol[] props, IMethodSymbol? ctor, string readerVariable, string indent)
    {
        var full = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var ctorParamProps = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        if (ctor is not null && ctor.Parameters.Length > 0)
        {
            sb.Append(indent).Append("var entity = new ").Append(full).Append("(");
            for (var i = 0; i < ctor.Parameters.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                var parameter = ctor.Parameters[i];
                var prop = FindPropertyForParameter(props, parameter);
                if (prop is null)
                    sb.Append("default");
                else
                {
                    ctorParamProps.Add(prop.Name);
                    sb.Append(ReadOrDefaultExpression(readerVariable, "ord_" + prop.Name, parameter.Type));
                }
            }
            sb.AppendLine(");");
        }
        else
        {
            var parameterless = type.InstanceConstructors.Any(c => c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public);
            if (!parameterless)
            {
                sb.AppendLine(indent + "throw new InvalidOperationException(\"ForgeORM source generator could not find a parameterless constructor or mappable constructor for " + Escape(type.ToDisplayString()) + ".\");");
                return;
            }
            sb.AppendLine(indent + "var entity = new " + full + "();");
        }

        foreach (var p in WritableProperties(type).Where(p => !ctorParamProps.Contains(p.Name)))
            sb.AppendLine(indent + "if (ord_" + p.Name + " >= 0 && !" + readerVariable + ".IsDBNull(ord_" + p.Name + ")) entity." + p.Name + " = " + ReadValueExpression(readerVariable, "ord_" + p.Name, p.Type) + ";");
    }

    private static void EmitSqlServerFirstExecutor(StringBuilder sb, INamedTypeSymbol type)
    {
        var full = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var safe = Safe(type);
        var props = Properties(type).ToArray();
        var ctor = PickConstructor(type, props);
        var ctorParamProps = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        sb.AppendLine();
        sb.AppendLine("    private static async ValueTask<" + full + "?> ExecuteSqlServerFirst_" + safe + "(string connectionString, string sql, object? parameters, int? timeoutSeconds, CancellationToken cancellationToken)");
        sb.AppendLine("    {");
        sb.AppendLine("        await using var connection = new SqlConnection(connectionString);");
        sb.AppendLine("        await connection.OpenAsync(cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("        await using var command = connection.CreateCommand();");
        sb.AppendLine("        command.CommandText = sql;");
        sb.AppendLine("        command.CommandType = CommandType.Text;");
        sb.AppendLine("        if (timeoutSeconds.HasValue) command.CommandTimeout = timeoutSeconds.Value;");
        sb.AppendLine("        var parameterName = FirstSqlParameterName(sql);");
        sb.AppendLine("        AddSqlParameter(command, parameterName, ExtractParameterValue(parameters, parameterName));");
        sb.AppendLine("        await using var reader = await command.ExecuteReaderAsync(CommandBehavior.SingleRow | CommandBehavior.SequentialAccess, cancellationToken).ConfigureAwait(false);");
        foreach (var p in props)
            sb.AppendLine("        var ord_" + p.Name + " = Ordinal(reader, \"" + Escape(ColumnName(p)) + "\");");
        sb.AppendLine("        if (!await reader.ReadAsync(cancellationToken).ConfigureAwait(false)) return default;");

        if (ctor is not null && ctor.Parameters.Length > 0)
        {
            sb.Append("        var entity = new ").Append(full).Append("(");
            for (var i = 0; i < ctor.Parameters.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                var parameter = ctor.Parameters[i];
                var prop = FindPropertyForParameter(props, parameter);
                if (prop is null)
                    sb.Append("default");
                else
                {
                    ctorParamProps.Add(prop.Name);
                    sb.Append(ReadOrDefaultExpression("reader", "ord_" + prop.Name, parameter.Type));
                }
            }
            sb.AppendLine(");");
        }
        else
        {
            var parameterless = type.InstanceConstructors.Any(c => c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public);
            if (!parameterless)
            {
                sb.AppendLine("        throw new InvalidOperationException(\"ForgeORM source generator could not find a parameterless constructor or a constructor whose parameter names match result columns for " + Escape(type.ToDisplayString()) + ".\");");
                sb.AppendLine("    }");
                return;
            }
            sb.AppendLine("        var entity = new " + full + "();");
        }

        foreach (var p in WritableProperties(type).Where(p => !ctorParamProps.Contains(p.Name)))
            sb.AppendLine("        if (ord_" + p.Name + " >= 0 && !reader.IsDBNull(ord_" + p.Name + ")) entity." + p.Name + " = " + ReadValueExpression("reader", "ord_" + p.Name, p.Type) + ";");

        sb.AppendLine("        return entity;");
        sb.AppendLine("    }");
    }

    private static void EmitBinder(StringBuilder sb, INamedTypeSymbol type)
    {
        var full = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var safe = Safe(type);
        sb.AppendLine();
        sb.AppendLine("    private sealed class Binder_" + safe + " : IForgeParameterBinder<" + full + ">");
        sb.AppendLine("    {");
        sb.AppendLine("        public void Bind(DbCommand command, " + full + " entity)");
        sb.AppendLine("        {");
        foreach (var p in Properties(type))
        {
            var dbType = DbTypeFor(p);
            var valueExpression = ParameterValueExpression(p);
            sb.AppendLine("            Add(command, \"" + Escape(p.Name) + "\", " + valueExpression + (dbType is null ? ");" : ", " + dbType + ");"));
            if (!string.Equals(ColumnName(p), p.Name, StringComparison.OrdinalIgnoreCase))
                sb.AppendLine("            Add(command, \"" + Escape(ColumnName(p)) + "\", " + valueExpression + (dbType is null ? ");" : ", " + dbType + ");"));
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static void Bind_" + safe + "(DbCommand command, object value)");
        sb.AppendLine("    {");
        sb.AppendLine("        var entity = (" + full + ")value;");
        foreach (var p in Properties(type))
        {
            var dbType = DbTypeFor(p);
            var valueExpression = ParameterValueExpression(p);
            sb.AppendLine("        Add(command, \"" + Escape(p.Name) + "\", " + valueExpression + (dbType is null ? ");" : ", " + dbType + ");"));
        }
        sb.AppendLine("    }");
    }

    private static void EmitSqlBuilder(StringBuilder sb, INamedTypeSymbol type)
    {
        var table = TableName(type);
        var safe = Safe(type);
        var columns = Properties(type).ToArray();
        var insertable = columns.Where(p => !IsComputed(p) && !IsKeyIdentity(p)).ToArray();
        var updateable = columns.Where(p => !IsComputed(p) && !IsKey(p)).ToArray();
        var key = columns.FirstOrDefault(IsKey) ?? columns.FirstOrDefault(p => string.Equals(p.Name, "Id", StringComparison.OrdinalIgnoreCase));

        sb.AppendLine();
        sb.AppendLine("    public static string SelectSql_" + safe + " => \"SELECT " + Escape(string.Join(", ", columns.Select(p => ColumnName(p)))) + " FROM " + Escape(table) + "\";");
        sb.AppendLine("    public static string InsertSql_" + safe + " => \"INSERT INTO " + Escape(table) + " (" + Escape(string.Join(", ", insertable.Select(ColumnName))) + ") VALUES (" + Escape(string.Join(", ", insertable.Select(p => "@" + p.Name))) + ")\";");
        if (key is not null)
            sb.AppendLine("    public static string UpdateSql_" + safe + " => \"UPDATE " + Escape(table) + " SET " + Escape(string.Join(", ", updateable.Select(p => ColumnName(p) + " = @" + p.Name))) + " WHERE " + Escape(ColumnName(key)) + " = @" + Escape(key.Name) + "\";");
        if (key is not null)
            sb.AppendLine("    public static string DeleteSql_" + safe + " => \"DELETE FROM " + Escape(table) + " WHERE " + Escape(ColumnName(key)) + " = @" + Escape(key.Name) + "\";");
    }

    private static void EmitGraphMetadata(StringBuilder sb, INamedTypeSymbol type)
    {
        sb.AppendLine("    public static string GraphMetadata_" + Safe(type) + " => \"" + Escape(type.ToDisplayString()) + "|" + Escape(TableName(type)) + "\";");
    }

    private static void EmitEntityMap(StringBuilder sb, INamedTypeSymbol type)
    {
        var cols = string.Join("|", Properties(type).Select(p => p.Name + ":" + ColumnName(p)));
        sb.AppendLine("    public static string EntityMap_" + Safe(type) + " => \"" + Escape(type.ToDisplayString()) + "|" + Escape(TableName(type)) + "|" + Escape(cols) + "\";");
    }

    private static bool IsKey(IPropertySymbol p) => p.GetAttributes().Any(a => a.AttributeClass?.Name is "ForgeKeyAttribute" or "KeyAttribute") || string.Equals(p.Name, "Id", StringComparison.OrdinalIgnoreCase);
    private static bool IsKeyIdentity(IPropertySymbol p) => IsKey(p);
    private static bool IsComputed(IPropertySymbol p) => p.GetAttributes().Any(a => a.AttributeClass?.Name is "ForgeComputedAttribute" or "ComputedAttribute");

    private static string ColumnName(IPropertySymbol property)
        => property.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name is "ForgeColumnAttribute" or "ColumnAttribute")?.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? property.Name;

    private static string TableName(INamedTypeSymbol type)
        => type.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name is "ForgeTableAttribute" or "TableAttribute")?.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? type.Name;



    private static string ParameterValueExpression(IPropertySymbol property)
    {
        var type = property.Type;
        var isNullableEnum = type is INamedTypeSymbol nullable
            && nullable.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T
            && nullable.TypeArguments[0].TypeKind == TypeKind.Enum;

        var enumType = isNullableEnum ? ((INamedTypeSymbol)type).TypeArguments[0] : type;
        if (enumType.TypeKind != TypeKind.Enum)
            return "entity." + property.Name;

        if (HasEnumStringStorage(property))
            return isNullableEnum
                ? "(entity." + property.Name + ".HasValue ? entity." + property.Name + ".Value.ToString() : null)"
                : "entity." + property.Name + ".ToString()";

        var castType = EnumUnderlyingTypeName((INamedTypeSymbol)enumType);
        return isNullableEnum
            ? "(entity." + property.Name + ".HasValue ? (object)(" + castType + ")entity." + property.Name + ".Value : null)"
            : "(" + castType + ")entity." + property.Name;
    }

    private static bool HasEnumStringStorage(IPropertySymbol property)
    {
        foreach (var attribute in property.GetAttributes())
        {
            var name = attribute.AttributeClass?.Name;
            if (name is not ("ForgeEnumStorageAttribute" or "EnumStorageAttribute"))
                continue;

            if (attribute.ConstructorArguments.Length > 0)
            {
                var value = attribute.ConstructorArguments[0].Value;
                if (value?.ToString()?.EndsWith("String", StringComparison.OrdinalIgnoreCase) == true)
                    return true;
                if (value is int i && i == 0)
                    return true;
            }
        }
        return false;
    }

    private static string EnumUnderlyingTypeName(INamedTypeSymbol enumType)
    {
        var underlying = enumType.EnumUnderlyingType;
        return underlying?.SpecialType switch
        {
            SpecialType.System_Byte => "byte",
            SpecialType.System_SByte => "sbyte",
            SpecialType.System_Int16 => "short",
            SpecialType.System_UInt16 => "ushort",
            SpecialType.System_Int64 => "long",
            SpecialType.System_UInt64 => "ulong",
            SpecialType.System_UInt32 => "uint",
            _ => "int"
        };
    }

    private static string? DbTypeFor(IPropertySymbol property)
    {
        var type = property.Type;
        if (type is INamedTypeSymbol named && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
            type = named.TypeArguments[0];
        if (type.TypeKind == TypeKind.Enum && HasEnumStringStorage(property))
            return "DbType.String";
        return DbTypeFor(type);
    }

    private static string? DbTypeFor(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
            type = named.TypeArguments[0];
        if (type.TypeKind == TypeKind.Enum)
            return EnumDbTypeFor((INamedTypeSymbol)type);
        return type.SpecialType switch
        {
            SpecialType.System_Int32 => "DbType.Int32",
            SpecialType.System_Int64 => "DbType.Int64",
            SpecialType.System_Int16 => "DbType.Int16",
            SpecialType.System_Boolean => "DbType.Boolean",
            SpecialType.System_String => "DbType.String",
            SpecialType.System_Decimal => "DbType.Decimal",
            SpecialType.System_Double => "DbType.Double",
            SpecialType.System_Single => "DbType.Single",
            SpecialType.System_DateTime => "DbType.DateTime2",
            _ => type.ToDisplayString() == "System.Guid" ? "DbType.Guid" : null
        };
    }

    private static string EnumDbTypeFor(INamedTypeSymbol enumType)
    {
        return enumType.EnumUnderlyingType?.SpecialType switch
        {
            SpecialType.System_Byte => "DbType.Byte",
            SpecialType.System_SByte => "DbType.SByte",
            SpecialType.System_Int16 => "DbType.Int16",
            SpecialType.System_UInt16 => "DbType.UInt16",
            SpecialType.System_Int64 => "DbType.Int64",
            SpecialType.System_UInt64 => "DbType.UInt64",
            SpecialType.System_UInt32 => "DbType.UInt32",
            _ => "DbType.Int32"
        };
    }

    private static string Safe(INamedTypeSymbol type)
        => type.ToDisplayString().Replace('.', '_').Replace('+', '_').Replace('<', '_').Replace('>', '_').Replace(',', '_').Replace(' ', '_');

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
