using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ForgeORM.SourceGenerated;

[Generator]
public sealed class ForgeOrmGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax,
                static (ctx, _) => GetTypeSymbol(ctx))
            .Where(static x => x is not null)!;

        var compilationAndTypes = context.CompilationProvider.Combine(candidates.Collect());

        context.RegisterSourceOutput(compilationAndTypes, static (spc, source) => Execute(spc, source.Left, source.Right!));
    }

    private static INamedTypeSymbol? GetTypeSymbol(GeneratorSyntaxContext context)
    {
        return context.Node switch
        {
            ClassDeclarationSyntax c => context.SemanticModel.GetDeclaredSymbol(c) as INamedTypeSymbol,
            RecordDeclarationSyntax r => context.SemanticModel.GetDeclaredSymbol(r) as INamedTypeSymbol,
            _ => null
        };
    }

    private static void Execute(SourceProductionContext context, Compilation compilation, IEnumerable<INamedTypeSymbol> allTypes)
    {
        var entityTypes = allTypes
            .Where(IsCandidateEntity)
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<INamedTypeSymbol>()
            .ToArray();

        if (entityTypes.Length == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Data.Common;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using ForgeORM.Core;");
        sb.AppendLine("namespace ForgeORM.Generated;");
        sb.AppendLine("public sealed class ForgeGeneratedAccessorProvider : IForgeSourceGeneratedAccessorProvider");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    public static void Register() => ForgeSourceGeneratedRegistry.Register(new ForgeGeneratedAccessorProvider());");
        sb.AppendLine("    public bool CanHandle(Type type) => type.FullName switch");
        sb.AppendLine("    {");
        foreach (var type in entityTypes)
            sb.AppendLine($"        \"{type.ToDisplayString()}\" => true,");
        sb.AppendLine("        _ => false");
        sb.AppendLine("    };");
        sb.AppendLine("    public Func<DbDataReader, object> GetReader(Type type, DbDataReader reader) => type.FullName switch");
        sb.AppendLine("    {");
        foreach (var type in entityTypes)
            sb.AppendLine($"        \"{type.ToDisplayString()}\" => r => Read_{Safe(type)}(r),");
        sb.AppendLine("        _ => throw new InvalidOperationException($\"No ForgeORM generated reader for {type.FullName}.\")");
        sb.AppendLine("    };");
        sb.AppendLine("    public Action<DbCommand, object> GetBinder(Type type) => type.FullName switch");
        sb.AppendLine("    {");
        foreach (var type in entityTypes)
            sb.AppendLine($"        \"{type.ToDisplayString()}\" => Bind_{Safe(type)},");
        sb.AppendLine("        _ => throw new InvalidOperationException($\"No ForgeORM generated binder for {type.FullName}.\")");
        sb.AppendLine("    };");


        sb.AppendLine("    private static void Add(DbCommand command, string name, object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        var p = command.CreateParameter(); p.ParameterName = \"@\" + name; p.Value = value ?? DBNull.Value; command.Parameters.Add(p);");
        sb.AppendLine("    }");

        foreach (var type in entityTypes)
        {
            EmitReader(sb, type);
            EmitBinder(sb, type);
            EmitSqlBuilder(sb, type);
            EmitGraphMetadata(sb, type);
        }

        sb.AppendLine("}");
        context.AddSource("ForgeORM.Generated.Accessors.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static bool IsCandidateEntity(INamedTypeSymbol type)
    {
        if (type.TypeKind != TypeKind.Class)
            return false;
        if (type.IsAbstract || type.DeclaredAccessibility != Accessibility.Public)
            return false;
        if (!HasPublicParameterlessConstructor(type))
            return false;

        return HasForgeTableAttribute(type) || type.GetMembers().OfType<IPropertySymbol>().Any(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic && IsScalar(p.Type));
    }

    private static bool HasPublicParameterlessConstructor(INamedTypeSymbol type)
        => type.InstanceConstructors.Any(c => c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public);

    private static bool HasForgeTableAttribute(INamedTypeSymbol type)
        => type.GetAttributes().Any(a => a.AttributeClass?.Name is "ForgeTableAttribute" or "TableAttribute");

    private static IEnumerable<IPropertySymbol> Properties(INamedTypeSymbol type)
        => type.GetMembers().OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic && p.GetMethod is not null && IsScalar(p.Type));

    private static IEnumerable<IPropertySymbol> WritableProperties(INamedTypeSymbol type)
        => Properties(type).Where(p => p.SetMethod is not null);

    private static bool IsScalar(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
            type = named.TypeArguments[0];
        if (type.TypeKind == TypeKind.Enum)
            return true;
        return type.SpecialType is SpecialType.System_String
            or SpecialType.System_Boolean
            or SpecialType.System_Byte
            or SpecialType.System_SByte
            or SpecialType.System_Int16
            or SpecialType.System_UInt16
            or SpecialType.System_Int32
            or SpecialType.System_UInt32
            or SpecialType.System_Int64
            or SpecialType.System_UInt64
            or SpecialType.System_Single
            or SpecialType.System_Double
            or SpecialType.System_Decimal
            or SpecialType.System_DateTime
            || type.ToDisplayString() is "System.Guid" or "System.DateTimeOffset" or "System.DateOnly" or "System.TimeOnly" or "System.TimeSpan" or "byte[]";
    }

    private static void EmitReader(StringBuilder sb, INamedTypeSymbol type)
    {
        var full = type.ToDisplayString();
        sb.AppendLine($"    private static object Read_{Safe(type)}(DbDataReader reader)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var entity = new {full}();");
        foreach (var p in WritableProperties(type))
        {
            var col = ColumnName(p);
            var csType = p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"        var ord_{p.Name} = reader.GetOrdinal(\"{col}\");");
            sb.AppendLine($"        if (!reader.IsDBNull(ord_{p.Name})) entity.{p.Name} = reader.GetFieldValue<{csType}>(ord_{p.Name});");
        }
        sb.AppendLine("        return entity;");
        sb.AppendLine("    }");
    }

    private static void EmitBinder(StringBuilder sb, INamedTypeSymbol type)
    {
        var full = type.ToDisplayString();
        sb.AppendLine($"    private static void Bind_{Safe(type)}(DbCommand command, object value)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var entity = ({full})value;");
        foreach (var p in Properties(type))
            sb.AppendLine($"        Add(command, \"{p.Name}\", entity.{p.Name});");
        sb.AppendLine("    }");
    }

    private static void EmitSqlBuilder(StringBuilder sb, INamedTypeSymbol type)
    {
        var insertable = Properties(type).Where(p => !p.Name.Equals("Id", StringComparison.OrdinalIgnoreCase)).ToArray();
        var table = TableName(type);
        sb.AppendLine($"    public static string InsertSql_{Safe(type)} => \"INSERT INTO {table} ({string.Join(", ", insertable.Select(ColumnName))}) VALUES ({string.Join(", ", insertable.Select(p => "@" + p.Name))});\";");
    }

    private static void EmitGraphMetadata(StringBuilder sb, INamedTypeSymbol type)
    {
        sb.AppendLine($"    public static string GraphMetadata_{Safe(type)} => \"{type.ToDisplayString()}|{TableName(type)}\";");
    }

    private static string ColumnName(IPropertySymbol property)
        => property.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name is "ForgeColumnAttribute" or "ColumnAttribute")?.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? property.Name;

    private static string TableName(INamedTypeSymbol type)
        => type.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name is "ForgeTableAttribute" or "TableAttribute")?.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? type.Name;

    private static string Safe(INamedTypeSymbol type)
        => type.ToDisplayString().Replace('.', '_').Replace('+', '_').Replace('<', '_').Replace('>', '_').Replace(',', '_').Replace(' ', '_');
}
