using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ForgeORM.SourceGenerators;

/// <summary>
/// ForgeORM compile-time mapper generator.
///
/// Completeness goals implemented here:
/// - class, record and struct DTO/entity materialization
/// - parameterless, positional-record and constructor-bound mapping
/// - nullable scalar support
/// - enum string/int materialization without GetFieldValue&lt;TEnum&gt;
/// - composite key discovery through [ForgeKey]/[Key] and conventions
/// - init/private-set safe object construction by using constructor/object initializers
/// - generated binders, generated SQL constants, entity maps and relationship metadata
/// - projection DTOs are supported by constructor-parameter name matching against columns/properties
/// - include/split-query support gets generated relationship metadata for convention-first graph loading
/// </summary>
[Generator]
public sealed class ForgeOrmGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax or StructDeclarationSyntax,
                static (ctx, _) => GetTypeSymbol(ctx))
            .Where(static x => x is not null)!;

        var compilationAndTypes = context.CompilationProvider.Combine(candidates.Collect());
        context.RegisterSourceOutput(compilationAndTypes, static (spc, source) => Execute(spc, source.Right!));
    }

    private static INamedTypeSymbol? GetTypeSymbol(GeneratorSyntaxContext context)
        => context.Node switch
        {
            ClassDeclarationSyntax c => context.SemanticModel.GetDeclaredSymbol(c) as INamedTypeSymbol,
            RecordDeclarationSyntax r => context.SemanticModel.GetDeclaredSymbol(r) as INamedTypeSymbol,
            StructDeclarationSyntax s => context.SemanticModel.GetDeclaredSymbol(s) as INamedTypeSymbol,
            _ => null
        };

    private static void Execute(SourceProductionContext context, IEnumerable<INamedTypeSymbol> allTypes)
    {
        var entityTypes = allTypes
            .Where(IsCandidateEntity)
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<INamedTypeSymbol>()
            .ToArray();

        if (entityTypes.Length == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using System.Data.Common;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using ForgeORM.Core;");
        sb.AppendLine("namespace ForgeORM.Generated;");
        sb.AppendLine();
        sb.AppendLine("public sealed class ForgeGeneratedAccessorProvider : IForgeSourceGeneratedAccessorProvider");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    public static void Register() => ForgeSourceGeneratedRegistry.Register(new ForgeGeneratedAccessorProvider());");
        sb.AppendLine();
        sb.AppendLine("    public bool CanHandle(Type type) => type.FullName switch");
        sb.AppendLine("    {");
        foreach (var type in entityTypes)
            sb.AppendLine("        \"" + Escape(type.ToDisplayString()) + "\" => true,");
        sb.AppendLine("        _ => false");
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public Func<DbDataReader, object> GetReader(Type type, DbDataReader reader) => type.FullName switch");
        sb.AppendLine("    {");
        foreach (var type in entityTypes)
            sb.AppendLine("        \"" + Escape(type.ToDisplayString()) + "\" => CreateReader_" + Safe(type) + "(reader),");
        sb.AppendLine("        _ => throw new InvalidOperationException($\"No ForgeORM generated reader for {type.FullName}.\")");
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public Action<DbCommand, object> GetBinder(Type type) => type.FullName switch");
        sb.AppendLine("    {");
        foreach (var type in entityTypes)
            sb.AppendLine("        \"" + Escape(type.ToDisplayString()) + "\" => Bind_" + Safe(type) + ",");
        sb.AppendLine("        _ => throw new InvalidOperationException($\"No ForgeORM generated binder for {type.FullName}.\")");
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public bool TryCreateReader<T>(DbDataReader reader, out Func<DbDataReader, T>? readerFunc)");
        sb.AppendLine("    {");
        foreach (var type in entityTypes)
        {
            sb.AppendLine("        if (typeof(T).FullName == \"" + Escape(type.ToDisplayString()) + "\")");
            sb.AppendLine("        {");
            sb.AppendLine("            readerFunc = (Func<DbDataReader, T>)(object)CreateReader_" + Safe(type) + "(reader);");
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
        }
        sb.AppendLine("        readerFunc = null;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public bool TryGetBinder(Type type, out Action<DbCommand, object>? binder)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!CanHandle(type))");
        sb.AppendLine("        {");
        sb.AppendLine("            binder = null;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine("        binder = GetBinder(type);");
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine();        sb.AppendLine("    public bool TryGetTypedBinder<T>(out IForgeParameterBinder<T>? binder)");
        sb.AppendLine("    {");
        foreach (var type in entityTypes)
        {
            sb.AppendLine("        if (typeof(T).FullName == \"" + Escape(type.ToDisplayString()) + "\")");
            sb.AppendLine("        {");
            sb.AppendLine("            binder = (IForgeParameterBinder<T>)(object)new Binder_" + Safe(type) + "();");
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
        }
        sb.AppendLine("        binder = null;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
        EmitHelpers(sb);

        foreach (var type in entityTypes)
        {
            EmitReaderFactory(sb, type);
            EmitBinder(sb, type);
            EmitSqlBuilder(sb, type);
            EmitGraphMetadata(sb, type);
            EmitEntityMap(sb, type);
            EmitProjectionMetadata(sb, type);
        }

        sb.AppendLine("}");
        context.AddSource("ForgeORM.Generated.Accessors.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitHelpers(StringBuilder sb)
    {
        sb.AppendLine("    private static int Ordinal(Type targetType, DbDataReader reader, string name)");
        sb.AppendLine("        => ForgeColumnOrdinalShapeCache.GetOrdinalOrMinusOne(targetType, reader, name);");
        sb.AppendLine();
        sb.AppendLine("    private static string Normalize(string value)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (string.IsNullOrWhiteSpace(value)) return string.Empty;");
        sb.AppendLine("        Span<char> buffer = value.Length <= 256 ? stackalloc char[value.Length] : new char[value.Length];");
        sb.AppendLine("        var index = 0;");
        sb.AppendLine("        foreach (var c in value)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (c == '_' || c == '-' || c == ' ' || c == '[' || c == ']' || c == '\\"') continue;");
        sb.AppendLine("            buffer[index++] = char.ToUpperInvariant(c);");
        sb.AppendLine("        }");
        sb.AppendLine("        return new string(buffer[..index]);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static void Add(DbCommand command, string name, object? value, DbType? dbType = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        var parameterName = name[0] == '@' || name[0] == ':' ? name : \"@\" + name;");
        sb.AppendLine("        for (var i = 0; i < command.Parameters.Count; i++)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (command.Parameters[i] is not DbParameter existing) continue;");
        sb.AppendLine("            if (string.Equals(existing.ParameterName.TrimStart('@', ':'), parameterName.TrimStart('@', ':'), StringComparison.OrdinalIgnoreCase))");
        sb.AppendLine("            {");
        sb.AppendLine("                if (dbType.HasValue) existing.DbType = dbType.Value;");
        sb.AppendLine("                existing.Value = value ?? DBNull.Value;");
        sb.AppendLine("                return;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        var p = command.CreateParameter();");
        sb.AppendLine("        p.ParameterName = parameterName;");
        sb.AppendLine("        if (dbType.HasValue) p.DbType = dbType.Value;");
        sb.AppendLine("        p.Value = value ?? DBNull.Value;");
        sb.AppendLine("        command.Parameters.Add(p);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static TEnum ReadEnum<TEnum>(DbDataReader reader, int ordinal) where TEnum : struct, Enum");
        sb.AppendLine("        => ForgeEnumReader.ReadEnum<TEnum>(reader, ordinal);");
        sb.AppendLine();
        sb.AppendLine("    private static TEnum? ReadNullableEnum<TEnum>(DbDataReader reader, int ordinal) where TEnum : struct, Enum");
        sb.AppendLine("        => ordinal < 0 || reader.IsDBNull(ordinal) ? null : ForgeEnumReader.ReadNullableEnum<TEnum>(reader, ordinal);");
        sb.AppendLine();
    }

    private static bool IsCandidateEntity(INamedTypeSymbol type)
    {
        if (type.TypeKind is not (TypeKind.Class or TypeKind.Struct)) return false;
        if (type.TypeKind == TypeKind.Class && type.IsAbstract) return false;
        if (type.DeclaredAccessibility != Accessibility.Public) return false;
        if (type.ContainingNamespace?.ToDisplayString().StartsWith("System", StringComparison.Ordinal) == true) return false;
        return HasForgeTableAttribute(type) || HasGenerateMapperAttribute(type) || HasForgeDtoAttribute(type) || HasForgeProjectionAttribute(type);
    }

    private static bool HasForgeTableAttribute(INamedTypeSymbol type)
        => type.GetAttributes().Any(a => a.AttributeClass?.Name is "ForgeTableAttribute" or "TableAttribute");

    private static bool HasGenerateMapperAttribute(INamedTypeSymbol type)
        => type.GetAttributes().Any(a => a.AttributeClass?.Name is "ForgeGenerateMapperAttribute" or "GenerateMapperAttribute");

    private static bool HasForgeDtoAttribute(INamedTypeSymbol type)
        => type.GetAttributes().Any(a => a.AttributeClass?.Name is "ForgeDtoAttribute" or "ForgeDTOAttribute" or "DtoAttribute" or "DTOAttribute");

    private static bool HasForgeProjectionAttribute(INamedTypeSymbol type)
        => type.GetAttributes().Any(a => a.AttributeClass?.Name is "ForgeProjectionAttribute" or "ProjectionAttribute");

    private static IEnumerable<IPropertySymbol> Properties(INamedTypeSymbol type)
        => type.GetMembers().OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic && p.GetMethod is not null && IsScalar(p.Type));

    private static IEnumerable<IPropertySymbol> SettableProperties(INamedTypeSymbol type)
        => Properties(type).Where(p => p.SetMethod is { DeclaredAccessibility: Accessibility.Public });

    private static bool IsScalar(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
            type = named.TypeArguments[0];
        if (type.TypeKind == TypeKind.Enum) return true;
        return type.SpecialType is SpecialType.System_String
            or SpecialType.System_Boolean
            or SpecialType.System_Byte
            or SpecialType.System_SByte
            or SpecialType.System_Int16
            or SpecialType.System_UInt16
            or SpecialType.System_Int32
            or SpecialType.System_UInt32
            or SpecialType.System_Int64
            or SpecialType.System_UInt64
            or SpecialType.System_Single
            or SpecialType.System_Double
            or SpecialType.System_Decimal
            or SpecialType.System_DateTime
            || type.ToDisplayString() is "System.Guid" or "System.DateTimeOffset" or "System.DateOnly" or "System.TimeOnly" or "System.TimeSpan" or "byte[]";
    }

    private static void EmitReaderFactory(StringBuilder sb, INamedTypeSymbol type)
    {
        var full = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var safe = Safe(type);
        var props = Properties(type).ToArray();
        var ctor = PickConstructor(type, props);
        var ctorParamProps = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        sb.AppendLine();
        sb.AppendLine("    private static Func<DbDataReader, object> CreateReader_" + safe + "(DbDataReader reader)");
        sb.AppendLine("    {");
        foreach (var p in props)
        {
            sb.AppendLine("        var ord_" + p.Name + " = Ordinal(typeof(" + full + "), reader, \"" + Escape(ColumnName(p)) + "\");");
            if (!string.Equals(ColumnName(p), p.Name, StringComparison.OrdinalIgnoreCase))
                sb.AppendLine("        if (ord_" + p.Name + " < 0) ord_" + p.Name + " = Ordinal(typeof(" + full + "), reader, \"" + Escape(p.Name) + "\");");
        }
        sb.AppendLine("        return r =>");
        sb.AppendLine("        {");

        var initProps = SettableProperties(type).ToList();
        if (ctor is not null && ctor.Parameters.Length > 0)
        {
            sb.Append("            var entity = new ").Append(full).Append("(");
            for (var i = 0; i < ctor.Parameters.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                var parameter = ctor.Parameters[i];
                var prop = FindPropertyForParameter(props, parameter);
                if (prop is null) sb.Append("default!");
                else
                {
                    ctorParamProps.Add(prop.Name);
                    sb.Append(ReadOrDefaultExpression("r", "ord_" + prop.Name, parameter.Type));
                }
            }
            sb.Append(")");
        }
        else
        {
            sb.Append("            var entity = new ").Append(full).Append("()");
        }

        var initializerProps = initProps.Where(p => !ctorParamProps.Contains(p.Name)).ToArray();
        if (initializerProps.Length > 0)
        {
            sb.AppendLine();
            sb.AppendLine("            {");
            for (var i = 0; i < initializerProps.Length; i++)
            {
                var p = initializerProps[i];
                sb.Append("                ").Append(p.Name).Append(" = ").Append(ReadOrDefaultExpression("r", "ord_" + p.Name, p.Type));
                sb.AppendLine(i == initializerProps.Length - 1 ? string.Empty : ",");
            }
            sb.AppendLine("            };");
        }
        else
        {
            sb.AppendLine(";");
        }

        sb.AppendLine("            return entity;");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    private static IMethodSymbol? PickConstructor(INamedTypeSymbol type, IPropertySymbol[] props)
    {
        var propsByName = props.ToDictionary(p => NormalizeKey(p.Name), p => p, StringComparer.OrdinalIgnoreCase);
        foreach (var p in props) propsByName[NormalizeKey(ColumnName(p))] = p;
        return type.InstanceConstructors
            .Where(c => c.DeclaredAccessibility == Accessibility.Public && c.Parameters.Length > 0)
            .OrderByDescending(c => c.Parameters.Length)
            .FirstOrDefault(c => c.Parameters.All(p => propsByName.ContainsKey(NormalizeKey(p.Name))));
    }

    private static IPropertySymbol? FindPropertyForParameter(IEnumerable<IPropertySymbol> props, IParameterSymbol parameter)
    {
        var normalized = NormalizeKey(parameter.Name);
        return props.FirstOrDefault(p => NormalizeKey(p.Name) == normalized || NormalizeKey(ColumnName(p)) == normalized);
    }

    private static string ReadOrDefaultExpression(string readerName, string ordinalName, ITypeSymbol type)
        => ordinalName + " >= 0 && !" + readerName + ".IsDBNull(" + ordinalName + ") ? " + ReadValueExpression(readerName, ordinalName, type) + " : default!";

    private static string ReadValueExpression(string readerName, string ordinalName, ITypeSymbol type)
    {
        var nullableNamed = type as INamedTypeSymbol;
        var isNullable = nullableNamed?.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;
        var actual = isNullable ? nullableNamed!.TypeArguments[0] : type;
        var full = actual.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        if (actual.TypeKind == TypeKind.Enum)
            return isNullable
                ? "ReadNullableEnum<" + full + ">(" + readerName + ", " + ordinalName + ")"
                : "ReadEnum<" + full + ">(" + readerName + ", " + ordinalName + ")";

        return full switch
        {
            "int" or "global::System.Int32" => readerName + ".GetInt32(" + ordinalName + ")",
            "long" or "global::System.Int64" => readerName + ".GetInt64(" + ordinalName + ")",
            "short" or "global::System.Int16" => readerName + ".GetInt16(" + ordinalName + ")",
            "byte" or "global::System.Byte" => readerName + ".GetByte(" + ordinalName + ")",
            "bool" or "global::System.Boolean" => readerName + ".GetBoolean(" + ordinalName + ")",
            "decimal" or "global::System.Decimal" => readerName + ".GetDecimal(" + ordinalName + ")",
            "double" or "global::System.Double" => readerName + ".GetDouble(" + ordinalName + ")",
            "float" or "global::System.Single" => readerName + ".GetFloat(" + ordinalName + ")",
            "string" or "global::System.String" => readerName + ".GetString(" + ordinalName + ")",
            "global::System.Guid" => readerName + ".GetGuid(" + ordinalName + ")",
            "global::System.DateTime" => readerName + ".GetDateTime(" + ordinalName + ")",
            _ => readerName + ".GetFieldValue<" + full + ">(" + ordinalName + ")"
        };
    }

    private static void EmitBinder(StringBuilder sb, INamedTypeSymbol type)
    {
        var full = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var safe = Safe(type);
        sb.AppendLine();
        sb.AppendLine("    private sealed class Binder_" + safe + " : IForgeParameterBinder<" + full + ">");
        sb.AppendLine("    {");
        sb.AppendLine("        public void Bind(DbCommand command, " + full + " entity)");
        sb.AppendLine("        {");
        foreach (var p in Properties(type))
        {
            var dbType = DbTypeFor(p);
            var valueExpression = ParameterValueExpression(p);
            sb.AppendLine("            Add(command, \"" + Escape(p.Name) + "\", " + valueExpression + (dbType is null ? ");" : ", " + dbType + ");"));
            if (!string.Equals(ColumnName(p), p.Name, StringComparison.OrdinalIgnoreCase))
                sb.AppendLine("            Add(command, \"" + Escape(ColumnName(p)) + "\", " + valueExpression + (dbType is null ? ");" : ", " + dbType + ");"));
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static void Bind_" + safe + "(DbCommand command, object value)");
        sb.AppendLine("    {");
        sb.AppendLine("        var entity = (" + full + ")value;");
        foreach (var p in Properties(type))
        {
            var dbType = DbTypeFor(p);
            var valueExpression = ParameterValueExpression(p);
            sb.AppendLine("        Add(command, \"" + Escape(p.Name) + "\", " + valueExpression + (dbType is null ? ");" : ", " + dbType + ");"));
            if (!string.Equals(ColumnName(p), p.Name, StringComparison.OrdinalIgnoreCase))
                sb.AppendLine("        Add(command, \"" + Escape(ColumnName(p)) + "\", " + valueExpression + (dbType is null ? ");" : ", " + dbType + ");"));
        }
        sb.AppendLine("    }");
    }

    private static void EmitSqlBuilder(StringBuilder sb, INamedTypeSymbol type)
    {
        var table = TableName(type);
        var safe = Safe(type);
        var columns = Properties(type).ToArray();
        var keys = ResolveKeys(type, columns).ToArray();
        var insertable = columns.Where(p => !IsComputed(p) && !keys.Contains(p, SymbolEqualityComparer.Default)).ToArray();
        var updateable = columns.Where(p => !IsComputed(p) && !keys.Contains(p, SymbolEqualityComparer.Default)).ToArray();
        var where = keys.Length == 0 ? "1 = 0" : string.Join(" AND ", keys.Select(k => ColumnName(k) + " = @" + k.Name));

        sb.AppendLine();
        sb.AppendLine("    public static string SelectSql_" + safe + " => \"SELECT " + Escape(string.Join(", ", columns.Select(ColumnName))) + " FROM " + Escape(table) + "\";");
        sb.AppendLine("    public static string SelectColumns_" + safe + " => \"" + Escape(string.Join(", ", columns.Select(ColumnName))) + "\";");
        sb.AppendLine("    public static string TableName_" + safe + " => \"" + Escape(table) + "\";");
        if (keys.Length > 0)
            sb.AppendLine("    public static string KeyColumns_" + safe + " => \"" + Escape(string.Join(",", keys.Select(ColumnName))) + "\";");
        sb.AppendLine("    public static string InsertSql_" + safe + " => \"INSERT INTO " + Escape(table) + " (" + Escape(string.Join(", ", insertable.Select(ColumnName))) + ") VALUES (" + Escape(string.Join(", ", insertable.Select(p => "@" + p.Name))) + ")\";");
        if (keys.Length > 0)
        {
            sb.AppendLine("    public static string UpdateSql_" + safe + " => \"UPDATE " + Escape(table) + " SET " + Escape(string.Join(", ", updateable.Select(p => ColumnName(p) + " = @" + p.Name))) + " WHERE " + Escape(where) + "\";");
            sb.AppendLine("    public static string DeleteSql_" + safe + " => \"DELETE FROM " + Escape(table) + " WHERE " + Escape(where) + "\";");
            sb.AppendLine("    public static string GetByIdSql_" + safe + " => \"SELECT TOP (1) " + Escape(string.Join(", ", columns.Select(ColumnName))) + " FROM " + Escape(table) + " WHERE " + Escape(where) + "\";");
        }
    }

    private static void EmitGraphMetadata(StringBuilder sb, INamedTypeSymbol type)
    {
        var props = type.GetMembers().OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic && p.GetMethod is not null && !IsScalar(p.Type))
            .Select(p => p.Name + ":" + p.Type.ToDisplayString())
            .ToArray();
        sb.AppendLine("    public static string GraphMetadata_" + Safe(type) + " => \"" + Escape(type.ToDisplayString()) + "|" + Escape(TableName(type)) + "|" + Escape(string.Join(";", props)) + "\";");
    }

    private static void EmitEntityMap(StringBuilder sb, INamedTypeSymbol type)
    {
        var props = Properties(type).ToArray();
        var keys = string.Join("|", ResolveKeys(type, props).Select(p => p.Name + ":" + ColumnName(p)));
        var cols = string.Join("|", props.Select(p => p.Name + ":" + ColumnName(p)));
        sb.AppendLine("    public static string EntityMap_" + Safe(type) + " => \"" + Escape(type.ToDisplayString()) + "|" + Escape(TableName(type)) + "|keys=" + Escape(keys) + "|" + Escape(cols) + "\";");
    }

    private static void EmitProjectionMetadata(StringBuilder sb, INamedTypeSymbol type)
    {
        var ctor = PickConstructor(type, Properties(type).ToArray());
        if (ctor is null) return;
        sb.AppendLine("    public static string ProjectionMap_" + Safe(type) + " => \"" + Escape(type.ToDisplayString()) + "|ctor=" + Escape(string.Join(",", ctor.Parameters.Select(p => p.Name + ":" + p.Type.ToDisplayString()))) + "\";");
    }

    private static IEnumerable<IPropertySymbol> ResolveKeys(INamedTypeSymbol type, IPropertySymbol[] properties)
    {
        var explicitKeys = properties.Where(p => p.GetAttributes().Any(a => a.AttributeClass?.Name is "ForgeKeyAttribute" or "KeyAttribute"))
            .OrderBy(p => KeyOrder(p)).ToArray();
        if (explicitKeys.Length > 0) return explicitKeys;
        var id = properties.FirstOrDefault(p => string.Equals(p.Name, "Id", StringComparison.OrdinalIgnoreCase));
        if (id is not null) return new[] { id };
        var entityId = properties.FirstOrDefault(p => string.Equals(p.Name, type.Name + "Id", StringComparison.OrdinalIgnoreCase));
        return entityId is not null ? new[] { entityId } : Array.Empty<IPropertySymbol>();
    }

    private static int KeyOrder(IPropertySymbol p)
        => p.GetAttributes().SelectMany(a => a.NamedArguments).FirstOrDefault(kv => kv.Key == "Order").Value.Value as int? ?? 0;

    private static bool IsComputed(IPropertySymbol p)
        => p.GetAttributes().Any(a => a.AttributeClass?.Name is "ForgeComputedAttribute" or "ComputedAttribute" or "DatabaseGeneratedAttribute");

    private static string ColumnName(IPropertySymbol property)
        => property.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name is "ForgeColumnAttribute" or "ColumnAttribute")?.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? property.Name;

    private static string TableName(INamedTypeSymbol type)
        => type.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name is "ForgeTableAttribute" or "TableAttribute")?.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? type.Name;

    private static string ParameterValueExpression(IPropertySymbol property)
    {
        var type = property.Type;
        var isNullableEnum = type is INamedTypeSymbol nullable
            && nullable.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T
            && nullable.TypeArguments[0].TypeKind == TypeKind.Enum;

        var enumType = isNullableEnum ? ((INamedTypeSymbol)type).TypeArguments[0] : type;
        if (enumType.TypeKind != TypeKind.Enum)
            return "entity." + property.Name;

        if (HasEnumStringStorage(property))
            return isNullableEnum
                ? "(entity." + property.Name + ".HasValue ? entity." + property.Name + ".Value.ToString() : null)"
                : "entity." + property.Name + ".ToString()";

        var castType = EnumUnderlyingTypeName((INamedTypeSymbol)enumType);
        return isNullableEnum
            ? "(entity." + property.Name + ".HasValue ? (object)(" + castType + ")entity." + property.Name + ".Value : null)"
            : "(" + castType + ")entity." + property.Name;
    }

    private static bool HasEnumStringStorage(IPropertySymbol property)
    {
        foreach (var attribute in property.GetAttributes())
        {
            var name = attribute.AttributeClass?.Name;
            if (name is not ("ForgeEnumStorageAttribute" or "EnumStorageAttribute"))
                continue;

            if (attribute.ConstructorArguments.Length > 0)
            {
                var value = attribute.ConstructorArguments[0].Value;
                if (value?.ToString()?.EndsWith("String", StringComparison.OrdinalIgnoreCase) == true)
                    return true;
                if (value is int i && i == 0)
                    return true;
            }
        }

        return false;
    }

    private static string EnumUnderlyingTypeName(INamedTypeSymbol enumType)
    {
        var underlying = enumType.EnumUnderlyingType;
        return underlying?.SpecialType switch
        {
            SpecialType.System_Byte => "byte",
            SpecialType.System_SByte => "sbyte",
            SpecialType.System_Int16 => "short",
            SpecialType.System_UInt16 => "ushort",
            SpecialType.System_Int64 => "long",
            SpecialType.System_UInt64 => "ulong",
            SpecialType.System_UInt32 => "uint",
            _ => "int"
        };
    }

    private static string? DbTypeFor(IPropertySymbol property)
    {
        var type = property.Type;
        if (type is INamedTypeSymbol named && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
            type = named.TypeArguments[0];

        if (type.TypeKind == TypeKind.Enum && HasEnumStringStorage(property))
            return "DbType.String";

        return DbTypeFor(type);
    }

    private static string? DbTypeFor(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
            type = named.TypeArguments[0];
        if (type.TypeKind == TypeKind.Enum)
            return EnumDbTypeFor((INamedTypeSymbol)type);
        return type.SpecialType switch
        {
            SpecialType.System_Int32 => "DbType.Int32",
            SpecialType.System_Int64 => "DbType.Int64",
            SpecialType.System_Int16 => "DbType.Int16",
            SpecialType.System_Boolean => "DbType.Boolean",
            SpecialType.System_String => "DbType.String",
            SpecialType.System_Decimal => "DbType.Decimal",
            SpecialType.System_Double => "DbType.Double",
            SpecialType.System_Single => "DbType.Single",
            SpecialType.System_DateTime => "DbType.DateTime2",
            _ => type.ToDisplayString() == "System.Guid" ? "DbType.Guid" : null
        };
    }


    private static string EnumDbTypeFor(INamedTypeSymbol enumType)
    {
        return enumType.EnumUnderlyingType?.SpecialType switch
        {
            SpecialType.System_Byte => "DbType.Byte",
            SpecialType.System_SByte => "DbType.SByte",
            SpecialType.System_Int16 => "DbType.Int16",
            SpecialType.System_UInt16 => "DbType.UInt16",
            SpecialType.System_Int64 => "DbType.Int64",
            SpecialType.System_UInt64 => "DbType.UInt64",
            SpecialType.System_UInt32 => "DbType.UInt32",
            _ => "DbType.Int32"
        };
    }

    private static string Safe(INamedTypeSymbol type)
        => type.ToDisplayString().Replace('.', '_').Replace('+', '_').Replace('<', '_').Replace('>', '_').Replace(',', '_').Replace(' ', '_');

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string NormalizeKey(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (var c in value)
            if (c != '_' && c != '-' && c != ' ' && c != '[' && c != ']' && c != '"') builder.Append(char.ToUpperInvariant(c));
        return builder.ToString();
    }
}
