using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ForgeORM.SourceGenerators;

[Generator]
public sealed class ForgeOrmGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
            static (ctx, _) => GetCandidate(ctx))
            .Where(static symbol => symbol is not null);

        context.RegisterSourceOutput(candidates, static (spc, symbol) =>
        {
            if (symbol is INamedTypeSymbol type)
                spc.AddSource($"{type.Name}.ForgeORM.g.cs", Emit(type));
        });
    }

    private static INamedTypeSymbol? GetCandidate(GeneratorSyntaxContext context)
    {
        var declaration = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(declaration) as INamedTypeSymbol;
        if (symbol is null)
            return null;

        foreach (var attribute in symbol.GetAttributes())
        {
            var name = attribute.AttributeClass?.ToDisplayString() ?? string.Empty;
            if (name is "ForgeORM.Abstractions.ForgeTableAttribute" or "ForgeTableAttribute" || name.EndsWith(".ForgeTableAttribute"))
                return symbol;
        }

        return null;
    }

    private static string Emit(INamedTypeSymbol type)
    {
        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        var fullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var safeName = fullName.Replace("global::", "").Replace('.', '_').Replace('<', '_').Replace('>', '_');
        var props = GetScalarProperties(type).ToArray();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Data.Common;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using ForgeORM.Core;");
        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("internal static class ").Append(safeName).AppendLine("_ForgeOrmGenerated");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine("    {");
        sb.Append("        ForgeGeneratedRegistry.RegisterReader<").Append(fullName).AppendLine(">(Read);");
        sb.Append("        ForgeGeneratedRegistry.RegisterParameterBinder<").Append(fullName).AppendLine(">(Bind);");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.Append("    private static ").Append(fullName).AppendLine(" Read(DbDataReader reader)");
        sb.AppendLine("    {");
        sb.Append("        var entity = new ").Append(fullName).AppendLine("();");
        foreach (var prop in props.Where(x => x.SetMethod is not null))
        {
            var colName = GetColumnName(prop);
            sb.Append("        var ord_").Append(prop.Name).Append(" = reader.GetOrdinal(\"").Append(Escape(colName)).AppendLine("\");");
            sb.Append("        if (!reader.IsDBNull(ord_").Append(prop.Name).AppendLine(") )");
            sb.Append("            entity.").Append(prop.Name).Append(" = ").Append(ReadExpression(prop)).AppendLine(";");
        }
        sb.AppendLine("        return entity;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.Append("    private static void Bind(DbCommand command, ").Append(fullName).AppendLine(" entity)");
        sb.AppendLine("    {");
        foreach (var prop in props.Where(x => x.GetMethod is not null))
        {
            sb.Append("        ForgeAdo.AddParameter(command, \"").Append(prop.Name).Append("\", entity.").Append(prop.Name).AppendLine(");");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static IEnumerable<IPropertySymbol> GetScalarProperties(INamedTypeSymbol type)
    {
        foreach (var member in type.GetMembers().OfType<IPropertySymbol>())
        {
            if (member.IsStatic || member.GetMethod is null)
                continue;

            var t = member.Type;
            var name = t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (t.IsValueType || name is "string" or "global::System.String" or "byte[]" or "global::System.Byte[]")
                yield return member;
        }
    }

    private static string GetColumnName(IPropertySymbol property)
    {
        foreach (var attr in property.GetAttributes())
        {
            var name = attr.AttributeClass?.ToDisplayString() ?? string.Empty;
            if ((name.EndsWith("ForgeColumnAttribute") || name.EndsWith(".ForgeColumnAttribute")) && attr.ConstructorArguments.Length > 0)
                return attr.ConstructorArguments[0].Value?.ToString() ?? property.Name;
        }
        return property.Name;
    }

    private static string ReadExpression(IPropertySymbol prop)
    {
        var type = prop.Type;
        var nullable = type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nts ? nts.TypeArguments[0] : type;
        var full = nullable.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var ord = $"ord_{prop.Name}";
        var expr = full switch
        {
            "int" or "global::System.Int32" => $"reader.GetInt32({ord})",
            "long" or "global::System.Int64" => $"reader.GetInt64({ord})",
            "short" or "global::System.Int16" => $"reader.GetInt16({ord})",
            "bool" or "global::System.Boolean" => $"reader.GetBoolean({ord})",
            "decimal" or "global::System.Decimal" => $"reader.GetDecimal({ord})",
            "double" or "global::System.Double" => $"reader.GetDouble({ord})",
            "float" or "global::System.Single" => $"reader.GetFloat({ord})",
            "string" or "global::System.String" => $"reader.GetString({ord})",
            "global::System.Guid" => $"reader.GetGuid({ord})",
            "global::System.DateTime" => $"reader.GetDateTime({ord})",
            _ => $"reader.GetFieldValue<{full}>({ord})"
        };
        return expr;
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
